/** Shell chrome copy: navigation, brand, footer, and shared UI defaults. */

export const zh = {
  shellTitle: '管理中心',
  brandSub: '管理端',
  logout: '退出登录',
  languageAria: '界面语言',
  navAria: '管理导航',
  moreAria: '更多管理功能',
  moreTitle: '更多管理功能',
  moreLabel: '更多',
  navUsers: '用户',
  navProjects: '项目',
  navPlugins: '插件',
  navModels: '模型',
  navUsage: '用量',
  navDocuments: '文档',
  navArchives: '归档',
  navTerminals: '终端',
  navSsh: 'SSH',
  navDeployment: '部署',
  navWebhooks: 'Webhook',
  navDesktops: '桌面',
  navAudit: '审计',
  loading: '正在加载',
  dialogClose: '关闭',
  cancel: '取消',
} satisfies Record<string, string>

export type ChromeCopyKey = keyof typeof zh

export const en = {
  shellTitle: 'Administration',
  brandSub: 'Admin',
  logout: 'Sign out',
  languageAria: 'Interface language',
  navAria: 'Administration navigation',
  moreAria: 'More administration features',
  moreTitle: 'More administration features',
  moreLabel: 'More',
  navUsers: 'Users',
  navProjects: 'Projects',
  navPlugins: 'Plugins',
  navModels: 'Models',
  navUsage: 'Usage',
  navDocuments: 'Documents',
  navArchives: 'Archives',
  navTerminals: 'Terminals',
  navSsh: 'SSH',
  navDeployment: 'Deployment',
  navWebhooks: 'Webhook',
  navDesktops: 'Desktops',
  navAudit: 'Audit',
  loading: 'Loading',
  dialogClose: 'Close',
  cancel: 'Cancel',
} satisfies Record<ChromeCopyKey, string>
