/** Archive conversation reader copy: chat timeline, tool cards, system events, and raw technical details. */

export const zh = {
  // Conversation header and stats
  conversationTitle: '对话记录',
  conversationDescription: '以聊天方式显示用户、助手和工具交互；运行配置等内部事件已收起。',
  statsAria: '对话统计',
  messageCount: '{count} 条消息',
  toolStepsCount: '{count} 个工具步骤',
  emptyTitle: '暂无可读对话',
  emptyBodyUnavailable: '该会话的正文暂时不可用，稍后可以重试。',
  emptyInternalOnly: '该归档只包含运行配置或内部事件。展开下方技术详情可查看完整记录。',
  noMessagesHint: '未发现用户或助手消息，以上内容是会话运行状态摘要。',
  partialHint: '当前只显示部分事件；导出记录可查看完整内容。',

  // Technical details
  techDetails: '查看技术详情',
  rawEventCount: '{count} 个原始事件',
  descendantsAria: '子会话与分支',
  sessionTree: '会话树',
  noDescendants: '没有可用的子会话记录。',
  rootSession: '根会话',
  childSession: '子会话',
  rawListAria: '原始事件列表',
  noRawEvents: '没有可用的原始事件。',

  // Timeline items
  roleUser: '用户',
  roleAssistant: '助手',
  interrupted: '回复在中途中断',
  roleTool: '工具',
  viewArguments: '查看参数',
  resultLabel: '结果',
  runFailed: '执行失败',
  nonTextResult: '工具已返回非文本结果，请查看技术详情。',
  toolResultPending: '尚未记录工具结果',
  roleSystem: '系统',
  toolCall: '工具调用',
  toolResult: '工具结果',
  toolErrorFallback: '工具返回错误结果',
  imagePlaceholder: '（图片）',

  // System event cards
  permissionPresetLabel: '权限设置',
  permissionPresetUpdated: '已更新权限策略',
  presetDetail: '预设：{name}',
  sandboxMode: '沙箱模式',
  sandboxReadOnly: '只读',
  sandboxWorkspaceWrite: '工作区可写',
  sandboxFullAccess: '完全访问',
  sandboxUpdated: '已更新运行权限',
  approvalPolicy: '审批策略',
  approvalAsk: '需要确认',
  approvalNever: '自动拒绝需审批操作',
  approvalPolicyUpdated: '已更新审批策略',
  planMode: '计划模式',
  planOn: '已开启',
  planOff: '已关闭',
  agentPreset: '助手配置',
  agentPresetSelected: '已选择运行配置',
  approvalAsked: '等待审批',
  approvalAwaitDetail: '需要确认后继续',
  toolNameDetail: '工具：{name}',
  approvalResult: '审批结果',
  approvalDecidedDone: '已完成审批',
  turnEnd: '运行结束',
  runAborted: '执行已中断',
  commandFailed: '命令失败',
  commandFailedDetail: '命令执行失败',
  presetCustom: '自定义',
  outcomeAllowedOnce: '本次允许',
  outcomeRejected: '已拒绝',
  outcomeCancelled: '已取消',
  outcomeUnavailable: '无法完成审批',

  // Raw event labels
  eventUserMessage: '用户消息',
  eventAssistantMessage: '助手消息',
  eventApprovalAsked: '审批请求',

  dateLocale: 'zh-CN',
} satisfies Record<string, string>

export type ArchiveConversationCopyKey = keyof typeof zh

export const en = {
  // Conversation header and stats
  conversationTitle: 'Conversation',
  conversationDescription: 'Shows user, assistant, and tool interactions as a chat; internal events such as run configuration are collapsed.',
  statsAria: 'Conversation statistics',
  messageCount: '{count} messages',
  toolStepsCount: '{count} tool steps',
  emptyTitle: 'No readable conversation',
  emptyBodyUnavailable: 'The conversation content is temporarily unavailable; try again later.',
  emptyInternalOnly: 'This archive only contains run configuration or internal events. Expand the technical details below to view the full record.',
  noMessagesHint: 'No user or assistant messages found; the content above is a summary of the session run state.',
  partialHint: 'Only some events are shown; export the record to view the full content.',

  // Technical details
  techDetails: 'View technical details',
  rawEventCount: '{count} raw events',
  descendantsAria: 'Child sessions and branches',
  sessionTree: 'Session tree',
  noDescendants: 'No child session records are available.',
  rootSession: 'Root session',
  childSession: 'Child session',
  rawListAria: 'Raw event list',
  noRawEvents: 'No raw events are available.',

  // Timeline items
  roleUser: 'User',
  roleAssistant: 'Assistant',
  interrupted: 'Reply interrupted',
  roleTool: 'Tool',
  viewArguments: 'View arguments',
  resultLabel: 'Result',
  runFailed: 'Execution failed',
  nonTextResult: 'The tool returned a non-text result; see the technical details.',
  toolResultPending: 'No tool result recorded yet',
  roleSystem: 'System',
  toolCall: 'Tool call',
  toolResult: 'Tool result',
  toolErrorFallback: 'The tool returned an error result',
  imagePlaceholder: '(image)',

  // System event cards
  permissionPresetLabel: 'Permission settings',
  permissionPresetUpdated: 'Permission policy updated',
  presetDetail: 'Preset: {name}',
  sandboxMode: 'Sandbox mode',
  sandboxReadOnly: 'Read-only',
  sandboxWorkspaceWrite: 'Workspace write',
  sandboxFullAccess: 'Full access',
  sandboxUpdated: 'Runtime permissions updated',
  approvalPolicy: 'Approval policy',
  approvalAsk: 'Confirmation required',
  approvalNever: 'Automatically reject actions that require approval',
  approvalPolicyUpdated: 'Approval policy updated',
  planMode: 'Plan mode',
  planOn: 'On',
  planOff: 'Off',
  agentPreset: 'Assistant configuration',
  agentPresetSelected: 'Run configuration selected',
  approvalAsked: 'Waiting for approval',
  approvalAwaitDetail: 'Confirmation required to continue',
  toolNameDetail: 'Tool: {name}',
  approvalResult: 'Approval result',
  approvalDecidedDone: 'Approval completed',
  turnEnd: 'Run ended',
  runAborted: 'Execution interrupted',
  commandFailed: 'Command failed',
  commandFailedDetail: 'Command execution failed',
  presetCustom: 'Custom',
  outcomeAllowedOnce: 'Allowed this time',
  outcomeRejected: 'Rejected',
  outcomeCancelled: 'Cancelled',
  outcomeUnavailable: 'Approval could not be completed',

  // Raw event labels
  eventUserMessage: 'User message',
  eventAssistantMessage: 'Assistant message',
  eventApprovalAsked: 'Approval request',

  dateLocale: 'en-US',
} satisfies Record<ArchiveConversationCopyKey, string>
