/** Shared user component copy: role and state badges, instance controls, and account dialogs. */

export const zh = {
  roleAdmin: '管理员',
  roleUser: '普通用户',
  granted: '已授予',
  notGranted: '未授予',
  accountActive: '正常',
  accountDisabled: '已禁用',
  stateReady: '运行中',
  stateStarting: '启动中',
  stateStopping: '停止中',
  stateStopped: '已停止',
  instanceActionsAria: '{name} 实例操作',
  instanceStart: '启动实例',
  instanceStop: '停止实例',
  instanceRestart: '重启实例',
  createTitle: '新建用户',
  createDescription: '创建登录账号并分配初始管理角色。',
  cancel: '取消',
  createSubmit: '创建用户',
  fieldUsername: '用户名',
  hintUsername: '用于登录，创建后不可修改。',
  fieldDisplayName: '显示名',
  placeholderOptional: '可选',
  fieldInitialPassword: '初始密码',
  fieldRole: '角色',
  editTitle: '编辑 {name}',
  editDescription: '更新显示名、管理角色和 Auto 审查资格。',
  saveChanges: '保存更改',
  autoReviewLabel: '允许选择 Auto 审查',
  autoReviewHint: '授予资格不会自动启用 Auto，也不会改变已有会话或新会话的默认权限。用户仍需在当前会话主动选择。',
  passwordTitle: '重置 {name} 的密码',
  passwordDescription: '新密码会立即替换当前登录密码。',
  passwordSubmit: '重置密码',
  fieldNewPassword: '新密码',
  disableTitle: '禁用用户',
  disableDescription: '禁用 {name} 后，该账号将无法继续登录。',
  disableConfirm: '确认禁用',
  deleteTitle: '删除用户',
  deleteDescription: '删除 {name} 后会立即撤销登录、停止实例并移除项目成员关系。审计、用量、协作会话和本地历史会保留，用户名不可复用；此操作不可恢复。',
  deleteConfirm: '确认删除',
} satisfies Record<string, string>

/** Shared user component locale key union. */
export type UsersComponentsCopyKey = keyof typeof zh

/** English dictionary checked against the Chinese key set. */
export const en = {
  roleAdmin: 'Admin',
  roleUser: 'User',
  granted: 'Granted',
  notGranted: 'Not granted',
  accountActive: 'Active',
  accountDisabled: 'Disabled',
  stateReady: 'Running',
  stateStarting: 'Starting',
  stateStopping: 'Stopping',
  stateStopped: 'Stopped',
  instanceActionsAria: '{name} instance actions',
  instanceStart: 'Start instance',
  instanceStop: 'Stop instance',
  instanceRestart: 'Restart instance',
  createTitle: 'New user',
  createDescription: 'Create a sign-in account and assign its initial admin role.',
  cancel: 'Cancel',
  createSubmit: 'Create user',
  fieldUsername: 'Username',
  hintUsername: 'Used to sign in; cannot be changed after creation.',
  fieldDisplayName: 'Display name',
  placeholderOptional: 'Optional',
  fieldInitialPassword: 'Initial password',
  fieldRole: 'Role',
  editTitle: 'Edit {name}',
  editDescription: 'Update the display name, admin role, and Auto review qualification.',
  saveChanges: 'Save changes',
  autoReviewLabel: 'Allow opting into Auto review',
  autoReviewHint: 'Granting the qualification does not enable Auto, nor does it change the default permissions of existing or new sessions; the user still has to opt in during the current session.',
  passwordTitle: 'Reset password for {name}',
  passwordDescription: 'The new password replaces the current sign-in password immediately.',
  passwordSubmit: 'Reset password',
  fieldNewPassword: 'New password',
  disableTitle: 'Disable user',
  disableDescription: 'Once {name} is disabled, the account can no longer sign in.',
  disableConfirm: 'Confirm disabling',
  deleteTitle: 'Delete user',
  deleteDescription: 'Deleting {name} immediately revokes sign-in, stops the instance, and removes project memberships. Audit, usage, collaborative sessions, and local history are kept; the username cannot be reused, and this action cannot be undone.',
  deleteConfirm: 'Confirm deletion',
} satisfies Record<UsersComponentsCopyKey, string>
