/** Archives page copy: header, empty-draft maintenance, filters, records table, detail dialog, and confirmations. */

export const zh = {
  // Page header and batch actions
  pageTitle: '归档对话',
  pageDescription: '统一查看和管理组织内已归档的个人与项目对话。',
  recordCount: '{count} 条记录',
  restoreSelected: '恢复所选',
  moveToTrash: '移入回收站',
  purgeSelected: '永久清理所选',
  invalidIdFilter: '用户 ID 和项目 ID 必须是正整数',
  actionPartialFailure: '有 {count} 条记录未完成：{details}',
  detailSeparator: '；',

  // Empty-draft maintenance section
  emptySectionTitle: '空白会话维护',
  emptyMetaScanned: '扫描完成',
  emptyMetaAdminOnly: '仅管理员可见',
  emptyHint: '先扫描一小时无可见内容的会话，再将选中项移入可恢复回收站。',
  scan: '扫描',
  trashSelectedEmpty: '清理选中空草稿',
  emptyConfirmTitle: '确认清理空草稿',
  emptyConfirmBody: '选中的 {count} 个空草稿将移入回收站，不会立即永久删除。正在编辑、已有内容或预览后更新的草稿会保留。',
  emptyTrashResult: '已移入回收站 {count} 个草稿；{skipped} 个草稿已不符合清理条件。',
  emptyTableAria: '空白会话维护列表',
  colSelect: '选择',
  colSession: '会话',
  colOwner: '归属',
  creatorLabel: '创建者',
  colUpdatedAt: '更新时间',
  colEvents: '事件',
  selectItem: '选择 {name}',
  personalConversation: '个人会话',
  projectRuntime: '项目 #{id}',
  personalRuntime: '个人运行时 #{id}',
  unknownUser: '未知用户',
  eventCount: '{count} 条事件',
  emptyScannedTitle: '当前没有符合条件的空白会话',
  emptyNotScannedTitle: '还没有扫描结果',
  emptyScannedDetail: '扫描完成，未发现超过一小时且没有可见内容的会话。',
  emptyNotScannedDetail: '点击“扫描”查找超过一小时且没有可见内容的会话。',

  // Filter section
  filterTitle: '筛选条件',
  stateLabel: '状态',
  stateArchived: '已归档',
  stateTrash: '回收站',
  statePurged: '已清理',
  stateAll: '全部',
  filterKeyword: '关键词',
  filterKeywordPlaceholder: '标题、正文或 Session ID',
  filterUserId: '用户 ID',
  filterUserIdAll: '全部用户',
  filterProjectId: '项目 ID',
  filterProjectIdAll: '全部项目',
  filterReset: '重置',
  filterApply: '应用筛选',

  // Records section and pagination
  recordsTitle: '归档记录',
  pageIndicator: '第 {page} 页',
  loadingRecords: '正在加载归档记录',
  emptyTitle: '没有匹配的归档对话',
  emptyDetailFiltered: '调整筛选条件后重试。',
  emptyDetailNone: '当前还没有归档对话。',
  selectedCount: '已选择 {count} 条',
  selectHint: '选择记录后可批量操作',
  selectAllPage: '全选本页',
  colConversation: '对话',
  colArchivedAt: '归档时间',
  colMessages: '消息',
  colView: '查看',
  prevPage: '上一页',
  nextPage: '下一页',
  noPreview: '暂无正文摘要',
  viewItem: '查看 {name}',
  messageCount: '{count} 条消息',
  syncPending: '等待实例确认',
  syncConflict: '操作未完成',
  syncUnavailable: '实例暂不可用',

  // Detail dialog
  dialogTitleFallback: '归档对话',
  dialogLoading: '正在加载对话内容',
  ungrouped: '未分组',
  exportAction: '导出',
  restore: '恢复',
  purge: '永久清理',
  loadingConversation: '正在读取对话',
  syncSynced: '已同步',
  syncUnavailableDetail: '运行时暂不可用',
  detailProject: '项目',
  recordStateLabel: '记录状态',
  syncStateLabel: '同步状态',
  purgedTitle: '对话已永久清理',
  purgedDetail: '正文和历史 Review 已清理，不能恢复。',

  // Action confirmation dialog
  confirmPurgeTitle: '永久清理归档对话？',
  confirmTrashTitle: '移入回收站？',
  confirmRestoreTitle: '恢复归档对话？',
  confirmPurgeDescription: '请求将在实例确认资源释放后清理整棵对话树及关联内容，不能恢复。仍有运行、子任务、终端或待处理输入时会拒绝，请先停止。',
  confirmTrashDescription: '对话会进入回收站，并在部署配置的保留窗口内可恢复。',
  confirmRestoreDescription: '对话会恢复到原来的 Workspace 位置。',

  dateLocale: 'zh-CN',
} satisfies Record<string, string>

export type ArchivesCopyKey = keyof typeof zh

export const en = {
  // Page header and batch actions
  pageTitle: 'Archived conversations',
  pageDescription: 'View and manage archived personal and project conversations across the organization.',
  recordCount: '{count} records',
  restoreSelected: 'Restore selected',
  moveToTrash: 'Move to trash',
  purgeSelected: 'Purge selected',
  invalidIdFilter: 'User ID and project ID must be positive integers',
  actionPartialFailure: '{count} records did not finish: {details}',
  detailSeparator: '; ',

  // Empty-draft maintenance section
  emptySectionTitle: 'Empty draft maintenance',
  emptyMetaScanned: 'Scan complete',
  emptyMetaAdminOnly: 'Admins only',
  emptyHint: 'Scan for conversations that have had no visible content for over an hour, then move the selected ones to the recoverable trash.',
  scan: 'Scan',
  trashSelectedEmpty: 'Clean up selected empty drafts',
  emptyConfirmTitle: 'Move empty drafts to trash?',
  emptyConfirmBody: 'Move {count} selected empty drafts to trash, without permanently deleting them. Drafts in use, with content, or updated after the preview stay intact.',
  emptyTrashResult: 'Moved {count} drafts to trash; {skipped} drafts no longer qualify.',
  emptyTableAria: 'Empty draft maintenance list',
  colSelect: 'Select',
  colSession: 'Conversation',
  colOwner: 'Owner',
  creatorLabel: 'Creator',
  colUpdatedAt: 'Updated',
  colEvents: 'Events',
  selectItem: 'Select {name}',
  personalConversation: 'Personal conversation',
  projectRuntime: 'Project #{id}',
  personalRuntime: 'Personal runtime #{id}',
  unknownUser: 'Unknown user',
  eventCount: '{count} events',
  emptyScannedTitle: 'No matching empty conversations',
  emptyNotScannedTitle: 'No scan results yet',
  emptyScannedDetail: 'Scan complete; no conversations older than an hour without visible content were found.',
  emptyNotScannedDetail: 'Select "Scan" to find conversations older than an hour with no visible content.',

  // Filter section
  filterTitle: 'Filters',
  stateLabel: 'Status',
  stateArchived: 'Archived',
  stateTrash: 'Trash',
  statePurged: 'Purged',
  stateAll: 'All',
  filterKeyword: 'Keyword',
  filterKeywordPlaceholder: 'Title, body, or session ID',
  filterUserId: 'User ID',
  filterUserIdAll: 'All users',
  filterProjectId: 'Project ID',
  filterProjectIdAll: 'All projects',
  filterReset: 'Reset',
  filterApply: 'Apply filters',

  // Records section and pagination
  recordsTitle: 'Archived records',
  pageIndicator: 'Page {page}',
  loadingRecords: 'Loading archived records',
  emptyTitle: 'No matching archived conversations',
  emptyDetailFiltered: 'Adjust the filters and try again.',
  emptyDetailNone: 'There are no archived conversations yet.',
  selectedCount: '{count} selected',
  selectHint: 'Select records to run batch actions',
  selectAllPage: 'Select all on this page',
  colConversation: 'Conversation',
  colArchivedAt: 'Archived at',
  colMessages: 'Messages',
  colView: 'View',
  prevPage: 'Previous page',
  nextPage: 'Next page',
  noPreview: 'No preview available',
  viewItem: 'View {name}',
  messageCount: '{count} messages',
  syncPending: 'Waiting for instance confirmation',
  syncConflict: 'Action incomplete',
  syncUnavailable: 'Instance temporarily unavailable',

  // Detail dialog
  dialogTitleFallback: 'Archived conversation',
  dialogLoading: 'Loading conversation content',
  ungrouped: 'Ungrouped',
  exportAction: 'Export',
  restore: 'Restore',
  purge: 'Purge',
  loadingConversation: 'Reading conversation',
  syncSynced: 'Synced',
  syncUnavailableDetail: 'Runtime temporarily unavailable',
  detailProject: 'Project',
  recordStateLabel: 'Record state',
  syncStateLabel: 'Sync state',
  purgedTitle: 'Conversation permanently purged',
  purgedDetail: 'The content and historical reviews have been purged and cannot be recovered.',

  // Action confirmation dialog
  confirmPurgeTitle: 'Purge archived conversations?',
  confirmTrashTitle: 'Move to trash?',
  confirmRestoreTitle: 'Restore archived conversations?',
  confirmPurgeDescription: 'The request purges the entire conversation tree and its related content once the instance confirms resource release; it cannot be undone. The request is refused while runs, subtasks, terminals, or pending inputs remain; stop them first.',
  confirmTrashDescription: 'The conversations move to the trash and can be restored within the retention window configured for the deployment.',
  confirmRestoreDescription: 'The conversations return to their original Workspace locations.',

  dateLocale: 'en-US',
} satisfies Record<ArchivesCopyKey, string>
