/** Audit page copy: filter form, event records, outcome badges, and audit metadata labels. */

export const zh = {
  // Page header and filter form
  pageTitle: '审计日志',
  pageDescription: '检索管理操作、认证事件、模型拒绝和网关请求结果。',
  metaFiltered: '已筛选',
  sectionFilters: '筛选条件',
  userIdLabel: '用户 ID',
  userIdPlaceholder: '全部用户',
  fieldActionPrefix: '操作前缀',
  actionPrefixPlaceholder: '例如 admin.',
  fieldFrom: '开始时间',
  fieldTo: '结束时间',
  filterReset: '重置',
  filterApply: '应用筛选',
  errorUserIdInvalid: '用户 ID 必须是正整数',

  // Event records
  eventsTitle: '事件记录',
  pageIndicator: '第 {page} 页',
  loadingEvents: '正在加载审计日志',
  emptyTitle: '没有匹配的记录',
  emptyDetailFiltered: '调整筛选条件后重试。',
  emptyDetail: '网关尚未写入审计事件。',
  columnTime: '时间',
  columnUser: '用户',
  columnAction: '操作',
  columnRequest: '请求',
  columnResult: '请求结果',
  columnMetadata: '对象与执行信息',
  columnIp: '来源 IP',
  systemActor: '系统',
  pagePrev: '上一页',
  pageNext: '下一页',

  // Request outcome badge
  resultSuccess: '请求成功',
  resultFailure: '请求失败',
  resultRecorded: '已记录',
  resultUnknown: '结果未知',

  // Metadata labels and boolean values
  noMetadata: '无附加信息',
  yes: '是',
  no: '否',
  metaId: '对象 ID',
  metaTargetId: '目标 ID',
  metaTargetKind: '目标类型',
  metaOwnerUserId: '所有者 ID',
  metaProjectId: '项目 ID',
  metaNodeId: '节点 ID',
  metaCatalogId: '文档 ID',
  metaRootSessionId: '根会话',
  metaSessionId: '会话',
  metaGrantId: '授权 ID',
  metaBackupId: '备份 ID',
  metaOperationId: '操作 ID',
  metaReceiptId: '原回执',
  metaRedispatchId: '重派回执',
  metaSubjectId: '配额对象 ID',
  metaSubjectType: '配额对象类型',
  metaRevision: '配置代次',
  metaGeneration: '实例代次',
  metaCount: '数量',
  metaRequested: '请求数量',
  metaSucceeded: '成功数量',
  metaTrashed: '回收数量',
  metaOpCount: '配置操作数',
  metaAllowed: '允许',
  metaShared: '共享',
  metaEnabled: '启用',
  metaAutoReviewEligible: 'Auto 资格',
  metaTerminalEnabled: '终端资格',
  metaSshEligible: 'SSH 资格',
  metaDesktopEligible: '桌面资格',
  metaStatus: '对象状态',
  metaState: '执行状态',
  metaMode: '访问模式',
  metaRole: '角色',
  metaAction: '动作',

  // Timestamp locale
  dateLocale: 'zh-CN',
} satisfies Record<string, string>

export type AuditCopyKey = keyof typeof zh

export const en = {
  // Page header and filter form
  pageTitle: 'Audit log',
  pageDescription: 'Search administrative operations, authentication events, model denials, and gateway request outcomes.',
  metaFiltered: 'Filtered',
  sectionFilters: 'Filters',
  userIdLabel: 'User ID',
  userIdPlaceholder: 'All users',
  fieldActionPrefix: 'Action prefix',
  actionPrefixPlaceholder: 'e.g. admin.',
  fieldFrom: 'Start time',
  fieldTo: 'End time',
  filterReset: 'Reset',
  filterApply: 'Apply filters',
  errorUserIdInvalid: 'The user ID must be a positive integer',

  // Event records
  eventsTitle: 'Event log',
  pageIndicator: 'Page {page}',
  loadingEvents: 'Loading audit events',
  emptyTitle: 'No matching records',
  emptyDetailFiltered: 'Adjust the filters and try again.',
  emptyDetail: 'The gateway has not written any audit events yet.',
  columnTime: 'Time',
  columnUser: 'User',
  columnAction: 'Action',
  columnRequest: 'Request',
  columnResult: 'Request result',
  columnMetadata: 'Object and execution details',
  columnIp: 'Source IP',
  systemActor: 'System',
  pagePrev: 'Previous page',
  pageNext: 'Next page',

  // Request outcome badge
  resultSuccess: 'Request succeeded',
  resultFailure: 'Request failed',
  resultRecorded: 'Recorded',
  resultUnknown: 'Outcome unknown',

  // Metadata labels and boolean values
  noMetadata: 'No additional details',
  yes: 'Yes',
  no: 'No',
  metaId: 'Object ID',
  metaTargetId: 'Target ID',
  metaTargetKind: 'Target type',
  metaOwnerUserId: 'Owner ID',
  metaProjectId: 'Project ID',
  metaNodeId: 'Node ID',
  metaCatalogId: 'Document ID',
  metaRootSessionId: 'Root session',
  metaSessionId: 'Session',
  metaGrantId: 'Grant ID',
  metaBackupId: 'Backup ID',
  metaOperationId: 'Operation ID',
  metaReceiptId: 'Original receipt',
  metaRedispatchId: 'Redispatch receipt',
  metaSubjectId: 'Quota subject ID',
  metaSubjectType: 'Quota subject type',
  metaRevision: 'Config revision',
  metaGeneration: 'Instance generation',
  metaCount: 'Count',
  metaRequested: 'Requested',
  metaSucceeded: 'Succeeded',
  metaTrashed: 'Trashed',
  metaOpCount: 'Config operations',
  metaAllowed: 'Allowed',
  metaShared: 'Shared',
  metaEnabled: 'Enabled',
  metaAutoReviewEligible: 'Auto qualification',
  metaTerminalEnabled: 'Terminal qualification',
  metaSshEligible: 'SSH qualification',
  metaDesktopEligible: 'Desktop eligibility',
  metaStatus: 'Object status',
  metaState: 'Execution state',
  metaMode: 'Access mode',
  metaRole: 'Role',
  metaAction: 'Action',

  // Timestamp locale
  dateLocale: 'en-US',
} satisfies Record<AuditCopyKey, string>
