/** Deployment control copy: maintenance windows, node convergence, backups, restores, and the operation ledger. */

export const zh = {
  operationFailed: '无法完成部署操作',
  pageTitle: '部署与迁移',
  pageDescription: '维护窗口协调全部写者收敛后再执行迁移或恢复；恢复完成会推进写纪元，使恢复前启动的进程自动停止写入。',
  refresh: '刷新',
  clusterTitle: '集群状态',
  writeEpochMeta: '写纪元 {value}',
  loadingCluster: '正在加载集群状态',
  modeServing: '服务中',
  modeMaintenance: '维护窗口',
  modeRestoring: '恢复未完成',
  writersQuiesced: '写者已收敛',
  writersNotQuiesced: '写者未收敛',
  maintenanceEpochMeta: '维护纪元 {value}',
  maintenanceReasonLine: '维护事由：{reason}',
  fieldReason: '维护事由',
  hintReason: '记录到控制行与操作台账；进入维护后变更请求返回 503。',
  placeholderReason: '例如：应用 v40→v41 迁移',
  enterMaintenance: '进入维护窗口',
  noticeEnteredMaintenance: '已进入维护窗口',
  exitMaintenance: '退出维护窗口',
  restoringHint: '恢复尚未完成，写入保持关闭。检查下方操作台账；失败时先处理原因，再由独立应用器重试。',
  nodesTitle: '计算节点',
  nodesMeta: '写者收敛要求实例已停止，且活跃节点心跳新鲜、已确认维护纪元、在途写者归零。请先处理运行会话、终端和任务，再停止实例。',
  nodesEmpty: '没有登记节点',
  nodesTableAria: '计算节点，可横向滚动',
  columnName: '名称',
  columnStatus: '状态',
  columnHeartbeat: '心跳',
  columnEpoch: '已确认纪元',
  columnInflight: '在途写者',
  columnRuntimes: '未停止实例',
  columnQuiesced: '收敛',
  columnActions: '操作',
  nodeActive: '在线',
  nodeDraining: '排空中',
  nodeOffline: '离线',
  heartbeatNever: '从未心跳',
  heartbeatSecondsAgo: '{value} 秒前',
  heartbeatMinutesAgo: '{value} 分钟前',
  inflightUnreported: '未上报',
  yes: '是',
  no: '否',
  noticeNodeDrained: '节点 {name} 已排空',
  noticeNodeRestored: '节点 {name} 已恢复',
  noticeNodeOffline: '节点 {name} 已标记离线',
  drain: '排空',
  restoreOnline: '恢复在线',
  markOffline: '标记离线',
  migrationsTitle: '数据库迁移',
  migrationsMeta: '由独立应用器 pg:deploy apply 在维护窗口内执行',
  migrationsUnavailable: '迁移目录不可用',
  migrationsSummary: '当前版本 {current}，已应用 {count} 个迁移。',
  migrationsDrift: '已应用迁移与打包文件不一致：{names}。先核对发布内容再继续。',
  migrationsNone: '没有待应用的迁移。',
  migrationsPending: '待应用：{names}',
  listSeparator: '、',
  backupsTitle: '备份',
  backupsMeta: '数据库转储与受管文件快照',
  backupNow: '立即备份',
  noticeBackupDone: '备份已完成并通过校验',
  loadingBackups: '正在加载备份',
  backupsEmptyTitle: '尚无备份',
  backupsEmptyDetail: '备份记录登记每次转储的迁移版本、写纪元与受管文件清单，供恢复时核对。',
  backupsTableAria: '备份记录，可横向滚动',
  columnPath: '路径',
  columnMigration: '迁移版本',
  columnWriteEpoch: '写纪元',
  columnSize: '大小',
  columnCreatedAt: '创建时间',
  viewBackupConfig: '查看备份配置',
  verify: '校验',
  noticeVerified: '校验完成',
  requestRestore: '请求恢复',
  backupRecording: '记录中',
  backupVerified: '已验证',
  backupFailed: '失败',
  backupRestored: '已用于恢复',
  operationsTitle: '操作台账',
  operationsMeta: '最近的部署操作',
  operationsEmpty: '尚无部署操作',
  operationsTableAria: '维护操作记录，可横向滚动',
  columnKind: '类型',
  columnNode: '节点',
  columnFinishedAt: '完成时间',
  columnError: '错误',
  configDialogTitle: '备份中的节点配置',
  configDialogDescription: '恢复业务数据保留当前节点配置。下列值仅用于审阅；如需采用，请在当前节点配置中保存并显式应用。凭据文件内容不会显示。',
  configEmpty: '该备份没有可审阅的节点配置',
  configVersions: '备份配置版本 {backup} · 当前运行版本 {current}',
  revisionUnknown: '未知',
  configIncompatible: '存储位置不兼容，恢复前必须先迁移并核验：{fields}',
  configTableAria: '备份配置与当前配置对比',
  columnSetting: '设置',
  columnBackupValue: '备份中的生效值',
  columnCurrentValue: '当前生效值',
  columnDiff: '差异',
  valueUnset: '未设置',
  diffSame: '相同',
  diffDifferent: '不同',
  restoreTitle: '请求恢复备份',
  restoreDescription: '独立应用器在维护窗口内执行：pg:deploy restore。它先完整保留当前受管数据，再恢复所选备份；当前节点配置和数据库连接保持不变，存储位置不兼容会拒绝。恢复后写纪元推进，旧进程必须重启。保护副本由管理员另行清理。',
  restoreConfirm: '登记恢复请求',
  noticeRestoreRequested: '恢复请求已登记；请进入维护窗口并运行 pg:deploy restore',
  exitDescription: '退出后变更请求恢复受理。确认迁移或恢复已验证完成。',
  exitConfirm: '退出维护',
  noticeExitedMaintenance: '已退出维护窗口',
} satisfies Record<string, string>

export type DeploymentCopyKey = keyof typeof zh

export const en = {
  operationFailed: 'The deployment operation could not be completed',
  pageTitle: 'Deployment and migration',
  pageDescription: 'The maintenance window quiesces every writer before migrations or restores run; a completed restore advances the write epoch so processes started before it stop writing.',
  refresh: 'Refresh',
  clusterTitle: 'Cluster status',
  writeEpochMeta: 'Write epoch {value}',
  loadingCluster: 'Loading cluster status',
  modeServing: 'Serving',
  modeMaintenance: 'Maintenance window',
  modeRestoring: 'Restore incomplete',
  writersQuiesced: 'Writers quiesced',
  writersNotQuiesced: 'Writers not quiesced',
  maintenanceEpochMeta: 'Maintenance epoch {value}',
  maintenanceReasonLine: 'Maintenance reason: {reason}',
  fieldReason: 'Maintenance reason',
  hintReason: 'Recorded on the control row and in the operation ledger; change requests return 503 while in maintenance.',
  placeholderReason: 'e.g. apply the v40→v41 migration',
  enterMaintenance: 'Enter maintenance window',
  noticeEnteredMaintenance: 'Entered the maintenance window',
  exitMaintenance: 'Exit maintenance window',
  restoringHint: 'The restore is not complete; writes stay closed. Check the operation ledger below; on failure, resolve the cause and retry with the standalone applier.',
  nodesTitle: 'Compute nodes',
  nodesMeta: 'Writer quiescence requires instances to be stopped, active node heartbeats fresh, the maintenance epoch acknowledged, and in-flight writers at zero. Handle running sessions, terminals, and tasks before stopping instances.',
  nodesEmpty: 'No nodes registered',
  nodesTableAria: 'Compute nodes, horizontally scrollable',
  columnName: 'Name',
  columnStatus: 'Status',
  columnHeartbeat: 'Heartbeat',
  columnEpoch: 'Acknowledged epoch',
  columnInflight: 'In-flight writers',
  columnRuntimes: 'Instances still running',
  columnQuiesced: 'Quiesced',
  columnActions: 'Actions',
  nodeActive: 'Online',
  nodeDraining: 'Draining',
  nodeOffline: 'Offline',
  heartbeatNever: 'No heartbeat yet',
  heartbeatSecondsAgo: '{value} seconds ago',
  heartbeatMinutesAgo: '{value} minutes ago',
  inflightUnreported: 'Not reported',
  yes: 'Yes',
  no: 'No',
  noticeNodeDrained: 'Node {name} drained',
  noticeNodeRestored: 'Node {name} restored',
  noticeNodeOffline: 'Node {name} marked offline',
  drain: 'Drain',
  restoreOnline: 'Restore online',
  markOffline: 'Mark offline',
  migrationsTitle: 'Database migrations',
  migrationsMeta: 'Run inside the maintenance window by the standalone applier pg:deploy apply',
  migrationsUnavailable: 'Migration catalog unavailable',
  migrationsSummary: 'Current version {current}; {count} migrations applied.',
  migrationsDrift: 'Applied migrations differ from the packaged files: {names}. Verify the release contents before continuing.',
  migrationsNone: 'No pending migrations.',
  migrationsPending: 'Pending: {names}',
  listSeparator: ', ',
  backupsTitle: 'Backups',
  backupsMeta: 'Database dumps and managed file snapshots',
  backupNow: 'Back up now',
  noticeBackupDone: 'Backup finished and verified',
  loadingBackups: 'Loading backups',
  backupsEmptyTitle: 'No backups yet',
  backupsEmptyDetail: 'Each backup record registers the dump\'s migration version, write epoch, and managed file manifest for verification during restore.',
  backupsTableAria: 'Backup records, horizontally scrollable',
  columnPath: 'Path',
  columnMigration: 'Migration version',
  columnWriteEpoch: 'Write epoch',
  columnSize: 'Size',
  columnCreatedAt: 'Created at',
  viewBackupConfig: 'View backup configuration',
  verify: 'Verify',
  noticeVerified: 'Verification complete',
  requestRestore: 'Request restore',
  backupRecording: 'Recording',
  backupVerified: 'Verified',
  backupFailed: 'Failed',
  backupRestored: 'Used for a restore',
  operationsTitle: 'Operation ledger',
  operationsMeta: 'Recent deployment operations',
  operationsEmpty: 'No deployment operations yet',
  operationsTableAria: 'Maintenance operation records, horizontally scrollable',
  columnKind: 'Type',
  columnNode: 'Node',
  columnFinishedAt: 'Finished at',
  columnError: 'Error',
  configDialogTitle: 'Node configuration in backup',
  configDialogDescription: 'Restoring business data keeps the current node configuration. The values below are for review only; to adopt them, save and explicitly apply them in the current node configuration. Credential file contents are not shown.',
  configEmpty: 'This backup has no node configuration to review',
  configVersions: 'Backup configuration revision {backup} · current running revision {current}',
  revisionUnknown: 'unknown',
  configIncompatible: 'Storage locations are incompatible; migrate and verify them before restoring: {fields}',
  configTableAria: 'Backup configuration compared to current configuration',
  columnSetting: 'Setting',
  columnBackupValue: 'Effective value in backup',
  columnCurrentValue: 'Current effective value',
  columnDiff: 'Difference',
  valueUnset: 'Not set',
  diffSame: 'Same',
  diffDifferent: 'Different',
  restoreTitle: 'Request backup restore',
  restoreDescription: 'The standalone applier runs inside the maintenance window: pg:deploy restore. It fully preserves current managed data before restoring the selected backup; the current node configuration and database connection stay unchanged, and incompatible storage locations are rejected. The write epoch advances after restore, so old processes must restart. Administrators clean up the protection copy separately.',
  restoreConfirm: 'Register restore request',
  noticeRestoreRequested: 'Restore request registered; enter the maintenance window and run pg:deploy restore',
  exitDescription: 'After exiting, change requests are accepted again. Confirm the migration or restore has been verified as complete.',
  exitConfirm: 'Exit maintenance',
  noticeExitedMaintenance: 'Exited the maintenance window',
} satisfies Record<DeploymentCopyKey, string>
