/** Desktops page copy: resource inventory, grant and queue supervision, and destructive confirms. */

export const zh = {
  pageTitle: '桌面协调',
  pageDescription: '查看交互桌面的独占授权、FIFO 排队与失联恢复状态。',
  resourceCount: '{count} 个资源',
  sectionResources: '桌面资源',
  refresh: '刷新',
  loadingResources: '正在加载桌面资源',
  emptyTitle: '没有桌面资源',
  emptyDetail: '尚无运行时申请交互桌面授权。',
  columnNode: '节点',
  columnDesktop: '桌面',
  labelState: '状态',
  labelFencingSeq: '栅栏序号',
  labelUpdated: '更新时间',
  detail: '详情',
  detailSectionTitle: '授权与排队 · {key}',
  loading: '加载中',
  grantsQueueMeta: '{grants} 项授权 / {queue} 项排队',
  loadingDetail: '正在加载桌面详情',
  detailErrorTitle: '无法读取详情',
  detailErrorDetail: '桌面资源可能已被清理。',
  clearUnavailable: '清理不可用状态',
  columnHolder: '持有人',
  columnRuntime: '运行时',
  columnFencing: '栅栏',
  columnHeartbeat: '心跳',
  columnAcquired: '获取时间',
  noGrants: '没有授权记录。',
  revoke: '撤权',
  columnPosition: '位次',
  columnQueued: '入队时间',
  revokeTitle: '撤权桌面授权',
  clearTitle: '清理不可用桌面',
  revokeDescription: '授权进入停止流程，持有人需在时限内确认输入已排空。操作会写入审计日志。',
  clearDescription: '强制释放无法确认的授权并恢复桌面可用，队首请求会被提升。操作会写入审计日志。',
  clearAction: '清理',
  holderUnknown: '未知',
  runtimeUser: '个人',
  runtimeProject: '项目',
  runtimeLine: '{kind} {id} · 代次 {generation}',
  stateAvailable: '可用',
  stateUnavailable: '不可用',
  grantHeld: '持有中',
  grantStopping: '停止中',
  grantRevoked: '已撤权',
  grantPending: '待确认',
  grantReleased: '已释放',
  queueQueued: '排队中',
  queuePromoted: '已提升',
  queueCancelled: '已取消',
  queueExpired: '已过期',
  dateLocale: 'zh-CN',
} satisfies Record<string, string>

export type DesktopsCopyKey = keyof typeof zh

export const en = {
  pageTitle: 'Desktop coordination',
  pageDescription: 'View exclusive grants, FIFO queueing, and lost-contact recovery state for interactive desktops.',
  resourceCount: '{count} resources',
  sectionResources: 'Desktop resources',
  refresh: 'Refresh',
  loadingResources: 'Loading desktop resources',
  emptyTitle: 'No desktop resources',
  emptyDetail: 'No runtime has requested an interactive desktop grant yet.',
  columnNode: 'Node',
  columnDesktop: 'Desktop',
  labelState: 'State',
  labelFencingSeq: 'Fencing sequence',
  labelUpdated: 'Updated',
  detail: 'Details',
  detailSectionTitle: 'Grants and queue · {key}',
  loading: 'Loading',
  grantsQueueMeta: '{grants} grants / {queue} queued',
  loadingDetail: 'Loading desktop details',
  detailErrorTitle: 'The details could not be read',
  detailErrorDetail: 'The desktop resource may have been cleaned up.',
  clearUnavailable: 'Clear unavailable state',
  columnHolder: 'Holder',
  columnRuntime: 'Runtime',
  columnFencing: 'Fencing',
  columnHeartbeat: 'Heartbeat',
  columnAcquired: 'Acquired',
  noGrants: 'No grant records.',
  revoke: 'Revoke',
  columnPosition: 'Position',
  columnQueued: 'Queued at',
  revokeTitle: 'Revoke desktop grant',
  clearTitle: 'Clean up unavailable desktop',
  revokeDescription: 'The grant enters the stop flow and the holder must confirm within the deadline that input has drained. The action is written to the audit log.',
  clearDescription: 'Force-release grants that cannot be confirmed and restore desktop availability; the head of the queue is promoted. The action is written to the audit log.',
  clearAction: 'Clean up',
  holderUnknown: 'Unknown',
  runtimeUser: 'Personal',
  runtimeProject: 'Project',
  runtimeLine: '{kind} {id} · generation {generation}',
  stateAvailable: 'Available',
  stateUnavailable: 'Unavailable',
  grantHeld: 'Held',
  grantStopping: 'Stopping',
  grantRevoked: 'Revoked',
  grantPending: 'Pending confirmation',
  grantReleased: 'Released',
  queueQueued: 'Queued',
  queuePromoted: 'Promoted',
  queueCancelled: 'Cancelled',
  queueExpired: 'Expired',
  dateLocale: 'en-US',
} satisfies Record<DesktopsCopyKey, string>
