/** Documents page copy: catalog filters, batch actions, detail dialog, and destructive confirms. */

export const zh = {
  errorStateChange: '文档状态变更失败',
  errorBatchFailed: '{count} 条记录处理失败',
  pageTitle: '文档',
  pageDescription: '组织级文档元数据、所有权、复制谱系和操作历史。文件内容只在授权作用域内查看。',
  refresh: '刷新',
  metricsAria: '文档汇总',
  metricActive: '活跃文档',
  stateTrash: '回收站',
  scopePersonal: '个人文档',
  scopeProject: '项目文档',
  metricFailures24h: '近 24 小时失败',
  filterSection: '筛选条件',
  labelQuery: '文件名或 ID',
  queryPlaceholder: '搜索元数据',
  labelScope: '作用域',
  scopeAll: '全部作用域',
  labelProject: '项目',
  projectAll: '全部项目',
  labelOwner: '所有者',
  ownerAll: '全部用户',
  labelState: '状态',
  stateActive: '活跃',
  statePurged: '已永久清理',
  stateAll: '全部',
  entryWithId: '{name}（#{id}）',
  reset: '重置',
  applyFilters: '应用筛选',
  catalogSection: '文档目录',
  recordCount: '{count} 条记录',
  batchAria: '批量文档操作',
  selectedCount: '已选 {count} 条',
  trash: '移入回收站',
  restore: '恢复',
  purge: '永久清理',
  clearSelection: '清除选择',
  loadingCatalog: '正在加载文档目录',
  emptyTitle: '没有匹配的文档',
  emptyDetail: '调整筛选条件后重试。',
  columnSelect: '选择',
  columnDocument: '文档',
  labelSize: '大小',
  labelSource: '来源',
  columnUpdated: '更新时间',
  selectRow: '选择 {name}',
  unassigned: '未分配',
  paginationAria: '文档分页',
  prevPage: '上一页',
  pageIndicator: '第 {page} 页',
  nextPage: '下一页',
  detailTitleFallback: '文档详情',
  detailDescription: '默认仅显示元数据；回收、恢复、永久清理和所有权变更都会写入审计日志。',
  close: '关闭',
  loadingDetail: '正在加载文档详情',
  labelCatalogId: '目录 ID',
  labelFileId: '文件 ID',
  labelLineageRoot: '谱系根',
  lineageCurrent: '当前根文档',
  labelAutoPurge: '自动清理',
  transferOwnership: '转移所有权',
  ownerLine: '所有者：{name}',
  personalOwnerHint: '（个人文档归属其所在账号）',
  historyHeading: '操作历史',
  historyEmpty: '暂无历史记录。',
  systemActor: '系统',
  copiesHeading: '复制记录',
  copiesEmpty: '暂无复制记录。',
  notGenerated: '未生成',
  trashTitle: '确认移入回收站',
  trashDescription: '文档会从作用域中移入可恢复回收站，并写入审计日志。保留期结束后才会永久清理。',
  cancel: '取消',
  purgeTitle: '永久清理文档？',
  purgeDescription: '该操作会永久删除回收站中的文档元数据，不能恢复。确认前请核对文档名称和作用域。',
  batchPurgeTitle: '永久清理所选文档？',
  batchPurgeDescription: '将永久清理 {count} 条回收站记录，不能恢复。',
  viewDetails: '查看详情',
  sourceUpload: '上传',
  sourceTransfer: '跨作用域复制',
  sourceLegacy: '历史导入',
  sourceAdmin: '管理员登记',
  dateLocale: 'zh-CN',
} satisfies Record<string, string>

export type DocumentsCopyKey = keyof typeof zh

export const en = {
  errorStateChange: 'The document state change failed',
  errorBatchFailed: 'Failed to process {count} records',
  pageTitle: 'Documents',
  pageDescription: 'Organization-wide document metadata, ownership, copy lineage, and operation history. File content is only visible inside an authorized scope.',
  refresh: 'Refresh',
  metricsAria: 'Document summary',
  metricActive: 'Active documents',
  stateTrash: 'Trash',
  scopePersonal: 'Personal documents',
  scopeProject: 'Project documents',
  metricFailures24h: 'Failures in the last 24 hours',
  filterSection: 'Filters',
  labelQuery: 'File name or ID',
  queryPlaceholder: 'Search metadata',
  labelScope: 'Scope',
  scopeAll: 'All scopes',
  labelProject: 'Project',
  projectAll: 'All projects',
  labelOwner: 'Owner',
  ownerAll: 'All users',
  labelState: 'Status',
  stateActive: 'Active',
  statePurged: 'Permanently purged',
  stateAll: 'All',
  entryWithId: '{name} (#{id})',
  reset: 'Reset',
  applyFilters: 'Apply filters',
  catalogSection: 'Document catalog',
  recordCount: '{count} records',
  batchAria: 'Batch document actions',
  selectedCount: '{count} selected',
  trash: 'Move to trash',
  restore: 'Restore',
  purge: 'Purge',
  clearSelection: 'Clear selection',
  loadingCatalog: 'Loading the document catalog',
  emptyTitle: 'No matching documents',
  emptyDetail: 'Adjust the filters and try again.',
  columnSelect: 'Select',
  columnDocument: 'Document',
  labelSize: 'Size',
  labelSource: 'Source',
  columnUpdated: 'Updated',
  selectRow: 'Select {name}',
  unassigned: 'Unassigned',
  paginationAria: 'Document pagination',
  prevPage: 'Previous page',
  pageIndicator: 'Page {page}',
  nextPage: 'Next page',
  detailTitleFallback: 'Document details',
  detailDescription: 'Only metadata is shown by default; trash, restore, purge, and ownership changes are written to the audit log.',
  close: 'Close',
  loadingDetail: 'Loading document details',
  labelCatalogId: 'Catalog ID',
  labelFileId: 'File ID',
  labelLineageRoot: 'Lineage root',
  lineageCurrent: 'Current root document',
  labelAutoPurge: 'Auto purge',
  transferOwnership: 'Transfer ownership',
  ownerLine: 'Owner: {name}',
  personalOwnerHint: ' (personal documents belong to their account)',
  historyHeading: 'Operation history',
  historyEmpty: 'No history yet.',
  systemActor: 'System',
  copiesHeading: 'Copy records',
  copiesEmpty: 'No copy records yet.',
  notGenerated: 'Not generated',
  trashTitle: 'Move to trash',
  trashDescription: 'The document moves from its scope into a recoverable trash and the action is written to the audit log. Permanent purge happens only after the retention period ends.',
  cancel: 'Cancel',
  purgeTitle: 'Purge the document permanently?',
  purgeDescription: 'This permanently deletes the document metadata in the trash and cannot be undone. Confirm the document name and scope first.',
  batchPurgeTitle: 'Purge the selected documents permanently?',
  batchPurgeDescription: 'This permanently purges {count} records in the trash and cannot be undone.',
  viewDetails: 'View details',
  sourceUpload: 'Upload',
  sourceTransfer: 'Cross-scope copy',
  sourceLegacy: 'Legacy import',
  sourceAdmin: 'Admin registration',
  dateLocale: 'en-US',
} satisfies Record<DocumentsCopyKey, string>
