/** Models page copy: governance tabs, the access-and-pricing dialog, and the personal registration audit. */

export const zh = {
  viewTabsAria: '模型治理视图',
  tabCatalog: '组织模型',
  tabGovernance: '权限与计价',
  tabPersonal: '个人登记',
  pageTitle: '模型治理',
  pageDescription: '统一管理组织 Provider、模型权限与计价；个人 BYOK 仅在个人运行时可用。',
  pageMeta: '{count} 个组织模型',
  editGovernance: '配置模型治理',
  governanceDialogDescription: 'Provider 和模型身份由组织模型插件维护；此处只配置运行权限和计价。',
  cancel: '取消',
  saveGovernance: '保存治理配置',
  switchEnabled: '启用模型',
  switchAdminDefault: '管理员默认允许',
  switchUserDefault: '普通用户默认允许',
  priceLabel: '单价（人民币元 / 百万 Token）',
  priceInput: '输入',
  priceOutput: '输出',
  priceCacheRead: '缓存读取',
  priceCacheWrite: '缓存写入',
  priceNotNegative: '单价必须是非负数',
  priceTooLarge: '单价超过可精确保存的范围',
  dateFormatInvalid: '日期格式必须为 YYYY-MM-DD',
  dateInvalid: '日期无效，请输入真实日期',
  personalTitle: '个人 Provider 与模型登记',
  personalMeta: '{providerCount} 个 Provider · {modelCount} 个模型',
  refresh: '刷新',
  personalNotice: '个人可以自由添加和管理 Provider 与模型；此页仅记录登记变化，不参与审批或权限限制。',
  filterAria: '个人登记筛选',
  filterUser: '用户',
  filterUserAria: '筛选用户',
  filterAllUsers: '全部用户',
  filterProvider: 'Provider',
  filterProviderPlaceholder: '按 Provider 筛选',
  filterProviderAria: '筛选 Provider',
  filterModel: '模型',
  filterModelPlaceholder: '按模型筛选',
  filterModelAria: '筛选模型',
  filterFrom: '开始日期',
  filterTo: '结束日期',
  filterAction: '动作',
  filterActionAria: '筛选动作',
  filterAllActions: '全部动作',
  filterReset: '重置',
  filterApply: '应用筛选',
  personalLoading: '正在加载个人登记记录',
  personalEmptyTitle: '暂无个人登记记录',
  personalEmptyDetail: '个人新增 Provider 或模型后，记录会显示在这里。',
  summaryEvents: '事件 {count}',
  summaryCreated: '新增 {count}',
  summaryModified: '修改 {count}',
  summaryDeleted: '删除 {count}',
  columnTime: '时间',
  columnUser: '用户',
  columnProvider: 'Provider',
  columnModel: '模型',
  columnAction: '动作',
  actionProviderCreated: '新增 Provider',
  actionProviderModified: '修改 Provider',
  actionProviderDeleted: '删除 Provider',
  actionModelCreated: '新增模型',
  actionModelModified: '修改模型',
  actionModelDeleted: '删除模型',
  userFallback: '用户 {id}',
  dateLocale: 'zh-CN',
  directoryTitle: '组织模型权限与计价',
  directoryMeta: '{count} 个模型',
  userException: '用户例外',
  userExceptionFor: '{name} 的例外',
  userOptionAdmin: '{name}（管理员）',
  userOptionUser: '{name}（用户）',
  directoryLoading: '正在加载模型治理配置',
  directoryEmptyTitle: '还没有组织模型',
  directoryEmptyDetail: '完整模型目录由组织 Provider 配置统一维护。',
  noUsersNotice: '暂无用户；角色默认与计价仍可配置。',
  columnStatus: '状态',
  columnRoleDefaults: '角色默认',
  columnPrice: '价格（元 / 百万 Token）',
  columnActionsAria: '操作',
  statusEnabled: '已启用',
  statusDisabled: '已停用',
} satisfies Record<string, string>

/** Models page locale key union. */
export type ModelsPageCopyKey = keyof typeof zh

/** English dictionary checked against the Chinese key set. */
export const en = {
  viewTabsAria: 'Model governance views',
  tabCatalog: 'Organization models',
  tabGovernance: 'Access and pricing',
  tabPersonal: 'Personal registrations',
  pageTitle: 'Model governance',
  pageDescription: 'Manage organization providers, model access, and pricing in one place; personal BYOK is available only in personal runtimes.',
  pageMeta: '{count} organization models',
  editGovernance: 'Configure model governance',
  governanceDialogDescription: 'Provider and model identities are maintained by the organization models plugin; only runtime access and pricing are configured here.',
  cancel: 'Cancel',
  saveGovernance: 'Save governance settings',
  switchEnabled: 'Enable model',
  switchAdminDefault: 'Allow admins by default',
  switchUserDefault: 'Allow regular users by default',
  priceLabel: 'Unit price (CNY per million tokens)',
  priceInput: 'Input',
  priceOutput: 'Output',
  priceCacheRead: 'Cache read',
  priceCacheWrite: 'Cache write',
  priceNotNegative: 'The unit price must be a non-negative number',
  priceTooLarge: 'The unit price exceeds the range that can be stored exactly',
  dateFormatInvalid: 'The date must use the YYYY-MM-DD format',
  dateInvalid: 'Invalid date; enter a real date',
  personalTitle: 'Personal provider and model registrations',
  personalMeta: '{providerCount} providers · {modelCount} models',
  refresh: 'Refresh',
  personalNotice: 'Users can freely add and manage providers and models; this page only records registration changes and does not take part in approval or access control.',
  filterAria: 'Personal registration filters',
  filterUser: 'User',
  filterUserAria: 'Filter by user',
  filterAllUsers: 'All users',
  filterProvider: 'Provider',
  filterProviderPlaceholder: 'Filter by provider',
  filterProviderAria: 'Filter by provider',
  filterModel: 'Model',
  filterModelPlaceholder: 'Filter by model',
  filterModelAria: 'Filter by model',
  filterFrom: 'Start date',
  filterTo: 'End date',
  filterAction: 'Action',
  filterActionAria: 'Filter by action',
  filterAllActions: 'All actions',
  filterReset: 'Reset',
  filterApply: 'Apply filters',
  personalLoading: 'Loading personal registrations',
  personalEmptyTitle: 'No personal registrations yet',
  personalEmptyDetail: 'When a user adds a provider or model, the record appears here.',
  summaryEvents: '{count} events',
  summaryCreated: '{count} created',
  summaryModified: '{count} modified',
  summaryDeleted: '{count} deleted',
  columnTime: 'Time',
  columnUser: 'User',
  columnProvider: 'Provider',
  columnModel: 'Model',
  columnAction: 'Action',
  actionProviderCreated: 'Provider added',
  actionProviderModified: 'Provider modified',
  actionProviderDeleted: 'Provider deleted',
  actionModelCreated: 'Model added',
  actionModelModified: 'Model modified',
  actionModelDeleted: 'Model deleted',
  userFallback: 'User {id}',
  dateLocale: 'en-US',
  directoryTitle: 'Organization model access and pricing',
  directoryMeta: '{count} models',
  userException: 'User exceptions',
  userExceptionFor: 'Exceptions for {name}',
  userOptionAdmin: '{name} (admin)',
  userOptionUser: '{name} (user)',
  directoryLoading: 'Loading model governance settings',
  directoryEmptyTitle: 'No organization models yet',
  directoryEmptyDetail: 'The complete model catalog is maintained in the organization provider settings.',
  noUsersNotice: 'No users yet; role defaults and pricing can still be configured.',
  columnStatus: 'Status',
  columnRoleDefaults: 'Role defaults',
  columnPrice: 'Price (yuan per million tokens)',
  columnActionsAria: 'Actions',
  statusEnabled: 'Enabled',
  statusDisabled: 'Disabled',
} satisfies Record<ModelsPageCopyKey, string>
