/** Node configuration section copy: groups, apply status, conflict errors, and the restart dialog. Field labels, help, and units ship from the server-owned NODE_CONFIG_FIELDS. */

export const zh = {
  groupNetwork: '访问与监听',
  groupPaths: '受管目录',
  groupCredentials: '凭据位置',
  groupRuntime: '实例生命周期与资源',
  statusPending: '等待独立应用器',
  statusApplying: '正在应用与验证',
  statusCompleted: '应用完成',
  statusFailed: '应用失败',
  errRevisionConflict: '配置已被其他操作更新，请重新读取并核对后再提交。',
  errIdentityMismatch: '表单所属节点已变化，请重新读取当前节点配置。',
  errApplyInProgress: '已有配置正在等待应用或执行，请待其完成后再修改。',
  errOperationRunning: '节点正在备份、恢复或应用配置，请待该操作结束后再试。',
  errRequiresMaintenance: '请先进入维护窗口，并停止全部运行时实例。',
  errPredatesRestore: '数据已经恢复到新的代次，请核对配置后重新发起应用。',
  errRestartFailed: 'Gateway 服务重启失败，请检查本机服务日志。',
  errRevisionUnconfirmed: 'Gateway 未确认期望的配置版本，请检查新监听地址和本机服务。',
  errPreviousRestored: '上一可用配置已恢复。',
  savedSave: '已保存待应用配置；当前进程仍使用原值。',
  savedApply: '应用请求已登记，等待独立应用器预检和重启验证。',
  sectionTitle: '当前节点配置',
  metaLoading: '读取服务器确认的组织与节点',
  metaNode: '节点 {node} · 配置版本 {revision} · 运行版本 {running}',
  loading: '正在读取节点配置',
  intro: '普通保存不重启服务。应用前请进入维护窗口、停止实例，并准备外部反向代理和目标目录。所有设置经独立应用器验证后重启生效。',
  stateEffective: '当前配置已生效',
  stateDesired: '有待应用配置',
  operationError: '配置版本 {revision}：{error}',
  filterLabel: '筛选节点设置',
  filterPlaceholder: '名称、用途或变量名',
  currentLine: '当前生效：{value} · 来源：{source}',
  notSet: '未设置',
  sourceBoot: '启动配置',
  sourceManaged: '受管配置版本 {revision}',
  saveButton: '保存待应用配置',
  applyButton: '应用并重启',
  rereadButton: '重新读取',
  configFileLead: '本机配置文件：',
  configFileCli: '。Web 失联时，在同一启动环境运行 ',
  configFileStatus: ' 查看状态，运行 ',
  configFileRecover: ' 验证并恢复上一可用配置。',
  applyDialogTitle: '应用节点配置并重启',
  applyDialogDescription: '独立应用器先核验维护状态、端口、数据库及数据目录，再重启当前节点 Gateway。连接会暂时中断；修改公开地址或端口前须先配置外部入口。失败时尝试恢复上一可用配置，失败证据保留。',
  cancel: '取消',
  applyConfirm: '确认应用并重启',
  applySummary: '将应用配置版本 {revision}，节点 {node}。',
  diffAria: '待应用配置变化',
  colSetting: '设置',
  colCurrent: '当前生效值',
  colDesired: '待应用值',
} satisfies Record<string, string>

/** Node configuration section locale key union. */
export type NodeConfigurationCopyKey = keyof typeof zh

/** English dictionary checked against the Chinese key set. */
export const en = {
  groupNetwork: 'Access and listening',
  groupPaths: 'Managed directories',
  groupCredentials: 'Credential locations',
  groupRuntime: 'Instance lifecycle and resources',
  statusPending: 'Waiting for the independent applier',
  statusApplying: 'Applying and verifying',
  statusCompleted: 'Apply completed',
  statusFailed: 'Apply failed',
  errRevisionConflict: 'The configuration was updated by another operation; read it again and verify before resubmitting.',
  errIdentityMismatch: 'The node this form belongs to has changed; read the current node configuration again.',
  errApplyInProgress: 'A configuration is already waiting to be applied or is being applied; wait for it to finish before editing.',
  errOperationRunning: 'The node is backing up, restoring, or applying configuration; retry after that operation finishes.',
  errRequiresMaintenance: 'Enter the maintenance window first and stop all runtime instances.',
  errPredatesRestore: 'The data was restored to a new generation; verify the configuration and request the apply again.',
  errRestartFailed: 'The Gateway service failed to restart; check the local service logs.',
  errRevisionUnconfirmed: 'Gateway did not confirm the desired configuration revision; check the new listen address and the local service.',
  errPreviousRestored: 'The previous working configuration has been restored.',
  savedSave: 'The pending configuration was saved; the running process still uses the previous values.',
  savedApply: 'The apply request was registered and is waiting for the independent applier to precheck and verify the restart.',
  sectionTitle: 'Current node configuration',
  metaLoading: 'Reading the server-confirmed organization and node',
  metaNode: 'Node {node} · configuration revision {revision} · running revision {running}',
  loading: 'Reading node configuration',
  intro: 'A plain save does not restart the service. Before applying, enter the maintenance window, stop the instances, and prepare the external reverse proxy and target directories. All settings take effect on restart after the independent applier validates them.',
  stateEffective: 'The current configuration is in effect',
  stateDesired: 'Configuration pending apply',
  operationError: 'Configuration revision {revision}: {error}',
  filterLabel: 'Filter node settings',
  filterPlaceholder: 'Name, purpose, or variable name',
  currentLine: 'Effective: {value} · source: {source}',
  notSet: 'Not set',
  sourceBoot: 'launch configuration',
  sourceManaged: 'managed configuration revision {revision}',
  saveButton: 'Save pending configuration',
  applyButton: 'Apply and restart',
  rereadButton: 'Read again',
  configFileLead: 'Local configuration file: ',
  configFileCli: '. If the web UI is unreachable, run ',
  configFileStatus: ' in the same launch environment to check status, and run ',
  configFileRecover: ' to verify and restore the previous working configuration.',
  applyDialogTitle: 'Apply node configuration and restart',
  applyDialogDescription: 'The independent applier first verifies the maintenance state, ports, database, and data directories, then restarts the current node Gateway. Connections are interrupted briefly; configure an external entry point before changing the public address or port. On failure it tries to restore the previous working configuration, and the failure evidence is kept.',
  cancel: 'Cancel',
  applyConfirm: 'Confirm apply and restart',
  applySummary: 'Configuration revision {revision} will be applied to node {node}.',
  diffAria: 'Pending configuration changes',
  colSetting: 'Setting',
  colCurrent: 'Current effective value',
  colDesired: 'Pending value',
} satisfies Record<NodeConfigurationCopyKey, string>
