/** Project detail page copy: header metadata, configuration ownership, usage, model access, members, and dialogs. */

export const zh = {
  // Page header and load states
  backToProjects: '返回项目',
  pageTitle: '项目详情',
  membersCount: '{count} 位成员',
  rename: '重命名',
  cancel: '取消',
  loadingProject: '正在加载项目',
  loadFailedTitle: '无法加载项目',
  loadFailedDetail: '请返回项目列表后重试。',
  invalidProjectId: '项目 ID 无效',

  // Origin metadata row
  metadataAria: '项目来源信息',
  originUser: '用户发起',
  originAdmin: '管理员发起',
  ownerValue: '所有者：{name}',
  ownerFallback: '组织管理',
  creatorValue: '创建者：{name}',
  creatorFallback: '未知',

  // Configuration ownership section
  configSectionTitle: '项目配置归属',
  configSectionMeta: '用户前端管理',
  openProjectSettings: '打开项目设置',
  configSummaryAria: '项目配置归属摘要',
  settingsLabel: '项目设置',
  settingsValue: '由用户前端的项目设置面板管理',
  settingsNote: '这里仅展示服务器资源和当前生效摘要，不提供用户个人偏好或项目逻辑配置编辑。',
  themePolicyField: '项目主题策略',
  themeFollowUser: '跟随成员偏好',
  themeLight: '强制浅色',
  themeDark: '强制深色',
  sharedRuntimeLabel: '共享运行时',
  runtimeStateUnknown: '状态未知',
  runtimeActionsAria: '项目实例操作',
  instanceStart: '启动实例',
  instanceStop: '停止实例',
  instanceRestart: '重启实例',
  providerLabel: '项目 Provider',
  providerNone: '未启用项目 Provider',
  providerCount: '{count} 个 · revision {revision}',
  serverDirectoryLabel: '服务器目录',
  serverDirectoryValue: '仅管理员可在 /admin 管理',
  configSectionHint: '管理员需要修改项目 Provider、运行时策略或界面策略时，请在用户端切换到该项目后打开「项目设置」；普通成员只能查看说明。',

  // Usage section and project configuration summary
  usageSectionTitle: '项目用量',
  monthLabel: '月份',
  configureQuota: '配置额度',
  loadingUsage: '正在加载项目用量',
  usageFailedTitle: '无法加载项目用量',
  usageFailedDetail: '请稍后重试或选择其他月份。',
  usageSummaryAria: '项目用量汇总',
  metricCalls: '调用次数',
  metricTokens: 'Token 总量',
  metricCost: '公司成本',
  metricMetering: '计量状态',
  meteringComplete: '完整',
  meteringMissing: '缺失 {count} 次',
  meteringDetail: '计量明细',
  inputTokensLabel: '输入 Token',
  outputTokensLabel: '输出 Token',
  cacheReadLabel: '缓存读取',
  cacheWriteLabel: '缓存写入',
  estimatedCostLabel: '估算成本',
  missingCallsLabel: '缺失计量',
  missingCallsValue: '{count} 次',
  priceLabel: '价格',
  effectiveQuotaTitle: '生效额度',
  effectiveQuotaNote: '告警不阻断调用',
  projectConfigTitle: '项目配置',
  quotaSourceField: '额度来源',
  tokenQuotaLabel: 'Token 额度',
  costQuotaLabel: '成本额度',
  companyCostQuotaLabel: '公司成本额度',
  pathLabel: '路径',
  originLabel: '来源',
  ownerLabel: '所有者',
  creatorLabel: '创建者',
  memberLabel: '成员',
  memberCountValue: '{count} 位',
  modelDefaultLabel: '模型默认规则',
  modelDefaultAll: '自动授权全部可用组织模型',
  modelDefaultExplicit: '仅授权项目明确选择的模型',
  modelAccessLabel: '模型权限',
  modelNotGranted: '未授权',

  // Member contributions section
  contributorsTitle: '成员贡献',
  contributorsMeta: '{count} 位已确认成员',
  loadingContributors: '正在加载成员贡献',
  contributorsHint: '贡献统计用于活动分析，不会重复计入项目账务或成员额度。历史未拆分调用：{tokens} Token。',
  contributorsEmptyTitle: '暂无已确认成员贡献',
  contributorsEmptyDetail: '项目调用仍会计入项目总量；没有 participant 身份的历史调用会保留为未拆分。',
  callsColumn: '调用',
  projectsColumn: '涉及项目',
  archivedSuffix: '（已归档）',

  // Project model access section
  modelAccessTitle: '项目模型权限',
  modelAccessMeta: '{assigned} / {total} 个模型已授权 · {mode} · 所有成员共享',
  modelModeAuto: '新增组织模型自动授权',
  modelModeManual: '按项目单独授权',
  enableAll: '全部开启',
  disableAll: '全部关闭',
  loadingModels: '正在加载项目模型权限',
  modelsEmptyTitle: '没有可分配的组织模型',
  modelsEmptyDetail: '请先在模型治理中配置完整的组织 Provider 和模型。',
  modelColumn: '模型',
  statusColumn: '运行状态',
  projectAccessColumn: '项目权限',
  modelAvailable: '可用',
  modelUnavailable: '暂不可用',
  modelGranted: '已授权',
  modelGrantedToProject: '已授权给项目',
  modelNotGrantedToProject: '未授权给项目',

  // Member permissions section
  membersTitle: '成员权限',
  membersMeta: '{count} 位可分配用户',
  membersEmptyTitle: '没有可分配用户',
  membersEmptyDetail: '先在用户页面创建账号，再配置项目权限。',
  userColumn: '用户',
  accountColumn: '账号',
  directoryAccessLabel: '目录权限',
  userActive: '正常',
  userDisabled: '已禁用',
  roleAdmin: '管理员',
  roleUser: '普通用户',
  permissionAria: '{name} 目录权限',
  permissionNone: '无权限',
  permissionRo: '只读',
  permissionRw: '读写',

  // Danger zone and delete confirmation
  deleteProject: '删除项目',
  deleteHint: '删除授权记录，不会删除宿主机上的项目目录或文件。',
  deleteDialogDescription: '删除 {name} 的授权记录？宿主机目录不会被删除。',
  confirmDelete: '确认删除',

  // Quota dialog
  quotaDialogTitle: '配置项目额度',
  quotaDialogDescription: '额度按自然月统计，在 80% 和 100% 产生告警，但不会阻断模型调用。',
  saveQuota: '保存额度',
  quotaInherit: '继承普通成员额度',
  quotaInheritHint: '跟随普通用户角色的默认额度',
  quotaIndependent: '项目独立额度',
  quotaIndependentHint: '为此项目单独设置 Token 和成本额度',
  monthlyTokensLabel: '每月 Token',
  monthlyCostLabel: '每月人民币元',
  quotaInheritNote: '此项目将使用普通成员角色的月度额度。',
  quotaModeLabel: '额度模式',
  quotaUnlimited: '无限制',
  quotaCustom: '自定义',
  quotaNoCap: '不设置月度上限。',
  quotaNoLimit: '不限',
  quotaTokenInvalid: 'Token 额度必须是非负整数',
  quotaCostInvalid: '成本额度必须是有效的非负数',

  // Rename dialog
  renameDialogTitle: '重命名项目',
  renameDialogDescription: '项目路径和成员权限不会改变。',
  saveName: '保存名称',
  projectNameLabel: '项目名称',

  // Runtime control dialog
  runtimeStartTitle: '启动项目实例',
  runtimeStopTitle: '停止项目实例',
  runtimeRestartTitle: '重启项目实例',
  runtimeStartDescription: '启动本节点的共享运行时。维护窗口中不允许启动。',
  runtimeStopDescription: '此操作影响项目 {name} 的所有在线成员，并会中断正在执行的 Agent、子任务和终端。停止后后台任务不会自动唤醒实例。',
  confirmExecute: '确认执行',

  // Remove member confirmation
  removeMemberTitle: '移除项目成员',
  removeMemberDescription: '移除 {name} 后，该用户将失去此项目目录的访问权限。',
  confirmRemove: '确认移除',
} satisfies Record<string, string>

export type ProjectDetailCopyKey = keyof typeof zh

export const en = {
  // Page header and load states
  backToProjects: 'Back to projects',
  pageTitle: 'Project details',
  membersCount: '{count} members',
  rename: 'Rename',
  cancel: 'Cancel',
  loadingProject: 'Loading project',
  loadFailedTitle: 'Unable to load project',
  loadFailedDetail: 'Return to the project list and try again.',
  invalidProjectId: 'Invalid project ID',

  // Origin metadata row
  metadataAria: 'Project origin information',
  originUser: 'User-initiated',
  originAdmin: 'Admin-initiated',
  ownerValue: 'Owner: {name}',
  ownerFallback: 'Organization',
  creatorValue: 'Creator: {name}',
  creatorFallback: 'Unknown',

  // Configuration ownership section
  configSectionTitle: 'Configuration ownership',
  configSectionMeta: 'Managed in the user frontend',
  openProjectSettings: 'Open project settings',
  configSummaryAria: 'Configuration ownership summary',
  settingsLabel: 'Project settings',
  settingsValue: 'Managed by the project settings panel in the user frontend',
  settingsNote: 'This page only shows server resources and the effective summary; personal preferences and project logic are not configured here.',
  themePolicyField: 'Project theme policy',
  themeFollowUser: 'Follow member preference',
  themeLight: 'Forced light',
  themeDark: 'Forced dark',
  sharedRuntimeLabel: 'Shared runtime',
  runtimeStateUnknown: 'Unknown',
  runtimeActionsAria: 'Project instance actions',
  instanceStart: 'Start instance',
  instanceStop: 'Stop instance',
  instanceRestart: 'Restart instance',
  providerLabel: 'Project Provider',
  providerNone: 'No project Provider enabled',
  providerCount: '{count} · revision {revision}',
  serverDirectoryLabel: 'Server directory',
  serverDirectoryValue: 'Managed by admins under /admin only',
  configSectionHint: 'To change the project Provider, runtime policy, or interface policy, switch to this project in the user frontend and open "Project settings"; regular members can only view this information.',

  // Usage section and project configuration summary
  usageSectionTitle: 'Project usage',
  monthLabel: 'Month',
  configureQuota: 'Configure quota',
  loadingUsage: 'Loading project usage',
  usageFailedTitle: 'Unable to load project usage',
  usageFailedDetail: 'Try again later or choose another month.',
  usageSummaryAria: 'Project usage summary',
  metricCalls: 'Calls',
  metricTokens: 'Total tokens',
  metricCost: 'Company cost',
  metricMetering: 'Metering status',
  meteringComplete: 'Complete',
  meteringMissing: '{count} missing',
  meteringDetail: 'Metering details',
  inputTokensLabel: 'Input tokens',
  outputTokensLabel: 'Output tokens',
  cacheReadLabel: 'Cache read',
  cacheWriteLabel: 'Cache write',
  estimatedCostLabel: 'Estimated cost',
  missingCallsLabel: 'Missing metering',
  missingCallsValue: '{count} calls',
  priceLabel: 'Pricing',
  effectiveQuotaTitle: 'Effective quota',
  effectiveQuotaNote: 'Alerts do not block calls',
  projectConfigTitle: 'Project configuration',
  quotaSourceField: 'Quota source',
  tokenQuotaLabel: 'Token quota',
  costQuotaLabel: 'Cost quota',
  companyCostQuotaLabel: 'Company cost quota',
  pathLabel: 'Path',
  originLabel: 'Origin',
  ownerLabel: 'Owner',
  creatorLabel: 'Creator',
  memberLabel: 'Members',
  memberCountValue: '{count}',
  modelDefaultLabel: 'Default model rule',
  modelDefaultAll: 'Automatically grants all available organization models',
  modelDefaultExplicit: 'Only grants models explicitly selected for the project',
  modelAccessLabel: 'Model access',
  modelNotGranted: 'Not granted',

  // Member contributions section
  contributorsTitle: 'Member contributions',
  contributorsMeta: '{count} confirmed members',
  loadingContributors: 'Loading member contributions',
  contributorsHint: 'Contribution statistics support activity analysis and are not double-counted toward project billing or member quotas. Historical unattributed calls: {tokens} tokens.',
  contributorsEmptyTitle: 'No confirmed member contributions yet',
  contributorsEmptyDetail: 'Project calls still count toward the project total; historical calls without a participant identity remain unattributed.',
  callsColumn: 'Calls',
  projectsColumn: 'Projects',
  archivedSuffix: ' (archived)',

  // Project model access section
  modelAccessTitle: 'Project model access',
  modelAccessMeta: '{assigned} / {total} models granted · {mode} · shared by all members',
  modelModeAuto: 'auto-grant for new organization models',
  modelModeManual: 'per-project grants',
  enableAll: 'Enable all',
  disableAll: 'Disable all',
  loadingModels: 'Loading project model access',
  modelsEmptyTitle: 'No organization models to assign',
  modelsEmptyDetail: 'Configure the organization Provider and its models in model governance first.',
  modelColumn: 'Model',
  statusColumn: 'Status',
  projectAccessColumn: 'Project access',
  modelAvailable: 'Available',
  modelUnavailable: 'Temporarily unavailable',
  modelGranted: 'Granted',
  modelGrantedToProject: 'Granted to project',
  modelNotGrantedToProject: 'Not granted to project',

  // Member permissions section
  membersTitle: 'Member permissions',
  membersMeta: '{count} assignable users',
  membersEmptyTitle: 'No users to assign',
  membersEmptyDetail: 'Create accounts on the Users page first, then configure project access.',
  userColumn: 'User',
  accountColumn: 'Account',
  directoryAccessLabel: 'Directory access',
  userActive: 'Active',
  userDisabled: 'Disabled',
  roleAdmin: 'Admin',
  roleUser: 'User',
  permissionAria: 'Directory access for {name}',
  permissionNone: 'None',
  permissionRo: 'Read-only',
  permissionRw: 'Read-write',

  // Danger zone and delete confirmation
  deleteProject: 'Delete project',
  deleteHint: 'Deletes the authorization record only; the project directory and files on the host are not removed.',
  deleteDialogDescription: 'Delete the authorization record for {name}? The host directory is not deleted.',
  confirmDelete: 'Delete',

  // Quota dialog
  quotaDialogTitle: 'Configure project quota',
  quotaDialogDescription: 'Quotas are counted per calendar month. Alerts fire at 80% and 100% but never block model calls.',
  saveQuota: 'Save quota',
  quotaInherit: 'Inherit regular member quota',
  quotaInheritHint: 'Follows the default quota of the regular user role',
  quotaIndependent: 'Independent project quota',
  quotaIndependentHint: 'Set token and cost quotas for this project only',
  monthlyTokensLabel: 'Tokens per month',
  monthlyCostLabel: 'CNY per month',
  quotaInheritNote: 'This project uses the monthly quota of the regular member role.',
  quotaModeLabel: 'Quota mode',
  quotaUnlimited: 'Unlimited',
  quotaCustom: 'Custom',
  quotaNoCap: 'No monthly cap.',
  quotaNoLimit: 'Unlimited',
  quotaTokenInvalid: 'The token quota must be a non-negative integer',
  quotaCostInvalid: 'The cost quota must be a valid non-negative number',

  // Rename dialog
  renameDialogTitle: 'Rename project',
  renameDialogDescription: 'The project path and member permissions stay unchanged.',
  saveName: 'Save name',
  projectNameLabel: 'Project name',

  // Runtime control dialog
  runtimeStartTitle: 'Start project instance',
  runtimeStopTitle: 'Stop project instance',
  runtimeRestartTitle: 'Restart project instance',
  runtimeStartDescription: 'Starts the shared runtime on this node. Starting is not allowed during a maintenance window.',
  runtimeStopDescription: 'This affects all online members of project {name} and interrupts running agents, subtasks, and terminals. Background tasks will not wake the instance after it stops.',
  confirmExecute: 'Confirm',

  // Remove member confirmation
  removeMemberTitle: 'Remove project member',
  removeMemberDescription: 'After removing {name}, this user loses access to the project directory.',
  confirmRemove: 'Remove',
} satisfies Record<ProjectDetailCopyKey, string>
