/** SSH page copy: target registry, project sharing, and field validation. */

export const zh = {
  operationFailed: '无法完成 SSH 操作',
  errorIntegerRange: '{label}必须是 {min} 到 {max} 之间的整数',
  errorRequired: '{label}不能为空',
  errorTooLong: '{label}不能超过 {max} 字符',
  errorAbsolutePath: '{label}必须是绝对路径',
  errorBootstrapPair: 'PTC 引导路径与摘要必须同时填写',
  errorBootstrapPath: 'PTC 引导路径必须是不超过 1024 字符的绝对路径',
  errorHostAlias: '主机别名必须以字母或数字开头，只能包含字母、数字、_、.、@、-',
  errorHelperHash: '助手摘要必须是 64 位小写十六进制',
  errorBootstrapHash: '引导摘要必须是 64 位小写十六进制',
  errorPasswordRef: '密码凭据引用必须以字母或下划线开头，只能包含字母、数字和下划线，最长 256 字符',
  labelName: '名称',
  labelHostAlias: '主机别名',
  labelPasswordRef: '密码凭据引用',
  labelNode: '远端 Node 可执行文件',
  labelHelper: '助手入口',
  labelHelperHash: '助手摘要',
  labelWorkspace: '远端默认工作区',
  labelBootstrapPath: 'PTC 引导路径',
  labelBootstrapHash: 'PTC 引导摘要',
  labelRequestTimeoutMs: '请求超时（毫秒）',
  labelMaxFrameBytes: '单帧上限（字节）',
  labelMaxPending: '并发请求上限',
  labelLeaseMs: '远端租约（毫秒）',
  labelRequestTimeout: '请求超时',
  labelMaxFrame: '单帧上限',
  labelLease: '远端租约',
  noticeCreated: 'SSH 目标已注册。',
  noticeUpdated: 'SSH 目标已更新。',
  noticeDisabled: '已停用 {name}。',
  noticeEnabled: '已启用 {name}。',
  noticeRemoved: '已删除 {name} 及其项目共享。',
  pageDescription: '登记的 OpenSSH 目标、项目共享和账号资格。',
  sectionTargets: '连接目标',
  refresh: '刷新',
  registerTarget: '注册目标',
  loading: '正在加载 SSH 目标',
  emptyTitle: '尚无 SSH 目标',
  emptyDetail: '登记部署拥有的 OpenSSH 别名后，具备资格的账号才能在受管运行时挂载远端执行环境。',
  tableAria: 'SSH 连接目标，可横向滚动',
  columnWorkspace: '远端工作区',
  columnShared: '共享项目',
  columnStatus: '状态',
  columnActions: '操作',
  projectSeparator: '、',
  statusEnabled: '已启用',
  statusDisabled: '已停用',
  edit: '编辑',
  shareAction: '项目共享',
  disable: '停用',
  enable: '启用',
  delete: '删除',
  cancel: '取消',
  save: '保存',
  titleRegister: '注册 SSH 目标',
  titleEdit: '编辑 {name}',
  titleShare: '共享 {name}',
  titleRemove: '删除 {name}',
  editDescription: '全部字段来自部署拥有的 OpenSSH 与已安装助手坐标；连接值只下发给通过资格校验的受管运行时。',
  hintName: '组织内唯一的管理显示名。',
  hintHostAlias: '包含既有用户、密钥和 known-hosts 配置的 OpenSSH 别名。',
  hintPasswordRef: '可选；填写连接运行时能解析的凭据名称，不填写密码。留空使用 OpenSSH 配置。',
  hintAbsolutePath: '绝对路径。',
  hintHelper: '已安装打包助手的绝对路径。',
  hintHelperHash: '助手包的 SHA-256；不匹配拒绝连接。',
  hintBootstrapPath: '可选；与摘要同时填写。',
  hintBootstrapHash: '可选；64 位小写十六进制。',
  shareDescription: '共享使项目运行时能够解析该目标；每位执行用户仍需独立 SSH 资格。',
  shareEmpty: '没有可共享的项目',
  removeDescription: '删除会同时移除全部项目共享；已挂载的连接在访问失效传播后被切断。',
} satisfies Record<string, string>

export type SshCopyKey = keyof typeof zh

export const en = {
  operationFailed: 'The SSH operation could not be completed',
  errorIntegerRange: '{label} must be an integer between {min} and {max}',
  errorRequired: '{label} must not be empty',
  errorTooLong: '{label} must not exceed {max} characters',
  errorAbsolutePath: '{label} must be an absolute path',
  errorBootstrapPair: 'Enter the PTC bootstrap path and digest together',
  errorBootstrapPath: 'The PTC bootstrap path must be an absolute path of at most 1024 characters',
  errorHostAlias: 'The host alias must start with a letter or digit and may contain only letters, digits, _, ., @, and -',
  errorHelperHash: 'The helper digest must be 64 lowercase hexadecimal characters',
  errorBootstrapHash: 'The bootstrap digest must be 64 lowercase hexadecimal characters',
  errorPasswordRef: 'The password credential reference must start with a letter or underscore, contain only letters, digits, and underscores, and be at most 256 characters',
  labelName: 'Name',
  labelHostAlias: 'Host alias',
  labelPasswordRef: 'Password credential reference',
  labelNode: 'Remote Node executable',
  labelHelper: 'Helper entry',
  labelHelperHash: 'Helper digest',
  labelWorkspace: 'Remote default workspace',
  labelBootstrapPath: 'PTC bootstrap path',
  labelBootstrapHash: 'PTC bootstrap digest',
  labelRequestTimeoutMs: 'Request timeout (ms)',
  labelMaxFrameBytes: 'Frame size limit (bytes)',
  labelMaxPending: 'Concurrent request limit',
  labelLeaseMs: 'Remote lease (ms)',
  labelRequestTimeout: 'Request timeout',
  labelMaxFrame: 'Frame size limit',
  labelLease: 'Remote lease',
  noticeCreated: 'The SSH target was registered.',
  noticeUpdated: 'The SSH target was updated.',
  noticeDisabled: '{name} was disabled.',
  noticeEnabled: '{name} was enabled.',
  noticeRemoved: '{name} and its project shares were deleted.',
  pageDescription: 'Registered OpenSSH targets, project sharing, and account qualification.',
  sectionTargets: 'Connection targets',
  refresh: 'Refresh',
  registerTarget: 'Register target',
  loading: 'Loading SSH targets',
  emptyTitle: 'No SSH targets yet',
  emptyDetail: 'Register a deployment-owned OpenSSH alias before qualified accounts can mount remote execution environments in managed runtimes.',
  tableAria: 'SSH connection targets, scrollable horizontally',
  columnWorkspace: 'Remote workspace',
  columnShared: 'Shared projects',
  columnStatus: 'Status',
  columnActions: 'Actions',
  projectSeparator: ', ',
  statusEnabled: 'Enabled',
  statusDisabled: 'Disabled',
  edit: 'Edit',
  shareAction: 'Project sharing',
  disable: 'Disable',
  enable: 'Enable',
  delete: 'Delete',
  cancel: 'Cancel',
  save: 'Save',
  titleRegister: 'Register SSH target',
  titleEdit: 'Edit {name}',
  titleShare: 'Share {name}',
  titleRemove: 'Delete {name}',
  editDescription: 'Every field comes from deployment-owned OpenSSH and installed helper coordinates; connection values are delivered only to managed runtimes that pass qualification.',
  hintName: 'An admin display name unique within the organization.',
  hintHostAlias: 'An OpenSSH alias with existing user, key, and known-hosts configuration.',
  hintPasswordRef: 'Optional; a credential name the connecting runtime can resolve, not a password. Leave empty to use the OpenSSH configuration.',
  hintAbsolutePath: 'Absolute path.',
  hintHelper: 'Absolute path of the installed packaged helper.',
  hintHelperHash: 'SHA-256 of the helper package; mismatches refuse the connection.',
  hintBootstrapPath: 'Optional; enter together with the digest.',
  hintBootstrapHash: 'Optional; 64 lowercase hexadecimal characters.',
  shareDescription: 'Sharing lets project runtimes resolve this target; every executing user still needs independent SSH qualification.',
  shareEmpty: 'No projects to share with',
  removeDescription: 'Deletion removes all project shares; mounted connections are cut once access revocation propagates.',
} satisfies Record<SshCopyKey, string>
