/** Steward space management page copy: admission rules, space state, and the member grant table. */

export const zh = {
  pageTitle: '维护空间',
  pageDescription: '常驻维护通道的准入管理：进入者须同时是活跃组织管理员并持有独立授权。',
  enabled: '已启用',
  disabled: '未启用',
  loading: '正在读取维护空间状态',
  refresh: '刷新',
  operationFailed: '操作失败',
  sectionRules: '准入规则',
  ruleAdmin: '必须是活跃组织管理员——管理员身份单独不足以进入',
  ruleGrant: '必须持有独立维护空间授权，缺省拒绝',
  ruleRevoke: '撤销授权或降级管理员角色都会立即终止准入，进行中的会话将重新核验',
  ruleAudit: '空间内全部操作留痕审计，数据库写语句需当场批准',
  sectionSpace: '空间状态',
  spaceName: '名称',
  spacePath: '工作区',
  spaceRuntime: '常驻运行时',
  spaceSeeded: '已播种',
  spaceMissing: '尚未播种——网关在启用后自动创建',
  spaceDisabled: '维护空间未启用。在部署环境中开启 HGW_STEWARD=on 后由网关自动播种。',
  runtimeReady: '就绪',
  runtimeStarting: '启动中',
  runtimeStopped: '已停止',
  runtimeError: '异常',
  sectionMembers: '授权成员',
  membersMeta: '{count} 名成员 · {effective} 名当前可进入',
  colUser: '用户',
  colRole: '角色',
  colGrant: '授权',
  colEffective: '准入状态',
  effectiveYes: '可进入',
  effectiveStale: '授权失效',
  effectiveNo: '未授权',
  grantFor: '授予 {name}',
  revokeFor: '撤销 {name} 的授权',
  grantTitle: '授予维护空间准入',
  grantDetail: '授予 {name} 进入常驻维护空间的权限。该通道可审计地操作部署数据库与项目代码，全部动作留痕。',
  revokeTitle: '撤销维护空间授权',
  revokeDetail: '撤销 {name} 的维护空间授权。撤销立即生效，进行中的会话将被要求重新核验。',
  confirmGrant: '授予',
  confirmRevoke: '撤销',
  clearStale: '清除失效授权',
  staleDetail: '该授权行存在但用户当前不符合管理员要求，准入已失效；可清除此行。',
  requiresAdmin: '需先提升为管理员',
  grantRejected: '授权被拒绝：{error}',
  noticeGranted: '已授予 {name} 维护空间准入。',
  noticeRevoked: '已撤销 {name} 的维护空间授权，运行中的会话已通知重新核验。',
  emptyTitle: '暂无成员',
  emptyDetail: '当前组织没有可列出的成员。',
} satisfies Record<string, string>

/** Steward page locale key union. */
export type StewardCopyKey = keyof typeof zh

/** English dictionary checked against the Chinese key set. */
export const en = {
  pageTitle: 'Maintenance space',
  pageDescription: 'Admission management for the resident maintenance channel: entry requires an active administrator role plus a separate grant.',
  enabled: 'Enabled',
  disabled: 'Disabled',
  loading: 'Loading maintenance-space state',
  refresh: 'Refresh',
  operationFailed: 'The operation failed',
  sectionRules: 'Admission rules',
  ruleAdmin: 'An active organization administrator role is required — the role alone does not admit',
  ruleGrant: 'A separate maintenance-space grant is required; absent it, entry is denied',
  ruleRevoke: 'Revoking the grant or downgrading the administrator role ends admission immediately; running sessions re-verify',
  ruleAudit: 'Every action in the space is audited, and database write statements need in-session approval',
  sectionSpace: 'Space state',
  spaceName: 'Name',
  spacePath: 'Workspace',
  spaceRuntime: 'Resident runtime',
  spaceSeeded: 'Seeded',
  spaceMissing: 'Not seeded yet — the gateway creates it once enabled',
  spaceDisabled: 'The maintenance space is disabled. Set HGW_STEWARD=on in the deployment environment and the gateway seeds it.',
  runtimeReady: 'Ready',
  runtimeStarting: 'Starting',
  runtimeStopped: 'Stopped',
  runtimeError: 'Error',
  sectionMembers: 'Authorized members',
  membersMeta: '{count} members · {effective} currently admitted',
  colUser: 'User',
  colRole: 'Role',
  colGrant: 'Grant',
  colEffective: 'Admission',
  effectiveYes: 'Admitted',
  effectiveStale: 'Grant ineffective',
  effectiveNo: 'Not granted',
  grantFor: 'Grant {name}',
  revokeFor: "Revoke {name}'s grant",
  grantTitle: 'Grant maintenance-space admission',
  grantDetail: 'Grant {name} admission to the resident maintenance space. The channel operates on the deployment database and project code under audit; every action is journaled.',
  revokeTitle: 'Revoke maintenance-space grant',
  revokeDetail: "Revoke {name}'s maintenance-space grant. Revocation takes effect immediately and running sessions are asked to re-verify.",
  confirmGrant: 'Grant',
  confirmRevoke: 'Revoke',
  clearStale: 'Clear stale grant',
  staleDetail: 'A grant row exists but the user no longer meets the administrator requirement; admission is ineffective and the row can be cleared.',
  requiresAdmin: 'Requires administrator role first',
  grantRejected: 'The grant was rejected: {error}',
  noticeGranted: 'Granted {name} maintenance-space admission.',
  noticeRevoked: "Revoked {name}'s maintenance-space grant; running sessions were notified to re-verify.",
  emptyTitle: 'No members',
  emptyDetail: 'The organization has no members to list.',
} satisfies Record<StewardCopyKey, string>
