/** Terminals page copy: scope selection, inventory states, and explicit close. */

export const zh = {
  stateStarting: '正在启动',
  stateRunning: '运行中',
  stateExited: '已退出',
  stateFailed: '失败',
  stateStopping: '正在清理',
  readFailed: '无法读取终端',
  targetUser: '用户 · {name} (@{username})',
  targetProject: '项目 · {name}',
  targetMismatch: '终端清单与选中范围不一致，请重新读取',
  noticeClosed: '进程已完成清理。',
  closeUnconfirmed: '{message}。尚未确认清理完成，请重新读取后重试。',
  pageTitle: '终端',
  pageDescription: '管理准入资格，查看当前节点上的终端并明确关闭。管理员不能读取或输入他人的终端。',
  sectionProcesses: '终端进程',
  scopeLabel: '运行范围',
  scopeAria: '终端运行范围',
  scopePlaceholder: '请选择用户或项目',
  scopeReload: '重新加载运行范围',
  refreshInventory: '刷新终端清单',
  loadingInventory: '正在读取终端清单',
  nodeLine: '节点 {node}',
  instanceStopped: '实例未运行；读取清单不会启动实例。',
  instanceGeneration: '实例代次 {generation}',
  empty: '没有保留的终端。',
  tableAria: '终端进程',
  columnTerminal: '终端',
  columnSession: '会话',
  columnCreator: '创建者',
  columnStatus: '状态',
  columnActions: '操作',
  localOperator: '本机操作者',
  creatorUser: '用户 #{id}',
  retryCleanup: '重试清理',
  closeTerminal: '关闭终端',
  closeDescription: '将终止终端 {id} 及其所属进程；运行中的命令会中断。隐藏标签不会执行此操作。',
  confirmClose: '确认关闭',
} satisfies Record<string, string>

export type TerminalsCopyKey = keyof typeof zh

export const en = {
  stateStarting: 'Starting',
  stateRunning: 'Running',
  stateExited: 'Exited',
  stateFailed: 'Failed',
  stateStopping: 'Cleaning up',
  readFailed: 'The terminals could not be read',
  targetUser: 'User · {name} (@{username})',
  targetProject: 'Project · {name}',
  targetMismatch: 'The terminal inventory does not match the selected scope; read it again',
  noticeClosed: 'The process finished cleanup.',
  closeUnconfirmed: '{message}. Cleanup was not confirmed; read the inventory again and retry.',
  pageTitle: 'Terminals',
  pageDescription: 'Manage admission qualification, view terminals on the current node, and close them explicitly. Administrators cannot read or type into other users\' terminals.',
  sectionProcesses: 'Terminal processes',
  scopeLabel: 'Scope',
  scopeAria: 'Terminal scope',
  scopePlaceholder: 'Select a user or project',
  scopeReload: 'Reload scopes',
  refreshInventory: 'Refresh terminal inventory',
  loadingInventory: 'Reading terminal inventory',
  nodeLine: 'Node {node}',
  instanceStopped: 'The instance is not running; reading the inventory does not start it.',
  instanceGeneration: 'Instance generation {generation}',
  empty: 'No terminals are retained.',
  tableAria: 'Terminal processes',
  columnTerminal: 'Terminal',
  columnSession: 'Session',
  columnCreator: 'Creator',
  columnStatus: 'Status',
  columnActions: 'Actions',
  localOperator: 'Local operator',
  creatorUser: 'User #{id}',
  retryCleanup: 'Retry cleanup',
  closeTerminal: 'Close terminal',
  closeDescription: 'This terminates terminal {id} and the process behind it; running commands are interrupted. Hidden tabs do not perform this action.',
  confirmClose: 'Confirm close',
} satisfies Record<TerminalsCopyKey, string>
