/** Usage page copy: monthly overview metrics, the per-user table, metering health, and the quota dialog. */

export const zh = {
  pageTitle: '模型用量',
  pageDescription: '个人用量用于额度与账务；项目贡献用于活动分析，不与项目总量重复相加。',
  monthLabel: '月份',
  configureQuota: '配置额度',
  summaryAria: '用量汇总',
  metricPersonalCalls: '个人调用',
  metricPersonalTokens: '个人 Token',
  metricProjectTokens: '项目 Token',
  metricProjectCost: '项目公司成本',
  metricUnattributedTokens: '未归属项目 Token',
  metricPersonalCost: '个人公司成本',
  metricQuotaAlerts: '额度告警',
  usersTitle: '用户用量',
  usersMeta: '{count} 位用户 · {timeZone}',
  loadingUsage: '正在加载用量',
  emptyTitle: '本月暂无用量',
  emptyDetail: '所选月份还没有收到模型调用计量记录。',
  columnUser: '用户',
  columnContribution: '项目贡献',
  columnPricing: '价格',
  columnMeteringQuota: '计量与额度',
  contributionValue: '{tokens}（{calls} 次）',
  healthTitle: '计量健康',
  loadingHealth: '正在加载计量健康',
  healthAria: '计量健康指标',
  healthMissing: '缺失计量',
  healthUnattributedCalls: '未归属项目调用',
  healthUnpriced: '未配置价格',
  healthHistoricalUnknown: '历史价格未知',
  healthMaxLag: '最大上报延迟',
  callsValue: '{count} 次',
  lagValue: '{value} 秒',
  quotaDialogTitle: '配置月度额度',
  quotaDialogDescription: '额度在 80% 和 100% 产生告警，但不会阻断模型调用。',
  cancel: '取消',
  saveQuota: '保存额度',
  subjectField: '配置对象',
  subjectRole: '角色默认',
  subjectUser: '指定用户',
  fieldRole: '角色',
  fieldUser: '用户',
  roleUser: '普通用户',
  roleAdmin: '管理员',
  noUsers: '暂无用户',
  userOption: '{name}（ID {id}）',
  tokenQuotaLabel: 'Token 额度',
  costQuotaLabel: '公司成本额度',
  monthlyTokensLabel: '每月 Token',
  monthlyCostLabel: '每月人民币元',
  identityArchived: '已归档历史',
  identityPersonal: '个人账务',
  tokenBreakdown: '输入 {input} · 输出 {output}',
  contributionNote: '{count} 次 · 不计入个人额度',
  quotaModeLabel: '额度模式',
  quotaModeInherit: '继承角色',
  quotaModeUnlimited: '无限制',
  quotaModeCustom: '自定义',
  quotaInheritNote: '使用该用户所属角色的额度。',
  quotaUnlimitedNote: '不设置月度上限。',
  quotaTokenInvalid: 'Token 额度必须是非负整数',
  quotaCostInvalid: '成本额度必须是有效的非负数',
  quotaLoading: '读取已保存的额度',
  retry: '重试',
} satisfies Record<string, string>

/** Usage page locale key union. */
export type UsagePageCopyKey = keyof typeof zh

/** English dictionary checked against the Chinese key set. */
export const en = {
  pageTitle: 'Model usage',
  pageDescription: 'Personal usage drives quotas and billing; project contributions support activity analysis and are not counted again toward project totals.',
  monthLabel: 'Month',
  configureQuota: 'Configure quota',
  summaryAria: 'Usage summary',
  metricPersonalCalls: 'Personal calls',
  metricPersonalTokens: 'Personal tokens',
  metricProjectTokens: 'Project tokens',
  metricProjectCost: 'Project company cost',
  metricUnattributedTokens: 'Unattributed project tokens',
  metricPersonalCost: 'Personal company cost',
  metricQuotaAlerts: 'Quota alerts',
  usersTitle: 'User usage',
  usersMeta: '{count} users · {timeZone}',
  loadingUsage: 'Loading usage',
  emptyTitle: 'No usage this month',
  emptyDetail: 'No model-call metering records have been received for the selected month.',
  columnUser: 'User',
  columnContribution: 'Project contribution',
  columnPricing: 'Pricing',
  columnMeteringQuota: 'Metering and quota',
  contributionValue: '{tokens} ({calls} calls)',
  healthTitle: 'Metering health',
  loadingHealth: 'Loading metering health',
  healthAria: 'Metering health metrics',
  healthMissing: 'Missing metering',
  healthUnattributedCalls: 'Unattributed project calls',
  healthUnpriced: 'Unpriced calls',
  healthHistoricalUnknown: 'Historical pricing unknown',
  healthMaxLag: 'Max reporting lag',
  callsValue: '{count} calls',
  lagValue: '{value} s',
  quotaDialogTitle: 'Configure monthly quota',
  quotaDialogDescription: 'Alerts fire at 80% and 100% but never block model calls.',
  cancel: 'Cancel',
  saveQuota: 'Save quota',
  subjectField: 'Subject',
  subjectRole: 'Role default',
  subjectUser: 'Specific user',
  fieldRole: 'Role',
  fieldUser: 'User',
  roleUser: 'User',
  roleAdmin: 'Admin',
  noUsers: 'No users yet',
  userOption: '{name} (ID {id})',
  tokenQuotaLabel: 'Token quota',
  costQuotaLabel: 'Company cost quota',
  monthlyTokensLabel: 'Tokens per month',
  monthlyCostLabel: 'CNY per month',
  identityArchived: 'Archived history',
  identityPersonal: 'Personal billing',
  tokenBreakdown: 'Input {input} · Output {output}',
  contributionNote: '{count} calls · not counted against the personal quota',
  quotaModeLabel: 'Quota mode',
  quotaModeInherit: 'Inherit from role',
  quotaModeUnlimited: 'Unlimited',
  quotaModeCustom: 'Custom',
  quotaInheritNote: 'Uses the quota of the role this user belongs to.',
  quotaUnlimitedNote: 'No monthly cap.',
  quotaTokenInvalid: 'The token quota must be a non-negative integer',
  quotaCostInvalid: 'The cost quota must be a valid non-negative number',
  quotaLoading: 'Reading stored quota',
  retry: 'Retry',
} satisfies Record<UsagePageCopyKey, string>
