/** User detail page copy: account header, qualification cards, model overrides, memberships, and quota. */

export const zh = {
  backToUsers: '返回用户列表',
  notFoundTitle: '用户不存在',
  notFoundDetail: '该账号可能已被删除。',
  pageTitle: '用户详情',
  pageTitleUser: '用户 · {name}',
  pageDescription: '@{username} · ID {id} · 端口 {port}',
  editAccount: '编辑账号',
  resetPassword: '重置密码',
  disable: '禁用',
  enable: '启用',
  deleteAction: '删除',
  loadingUser: '正在加载用户',
  sectionAccount: '账号与实例',
  defUsername: '用户名',
  defDisplayName: '显示名',
  notSet: '未设置',
  defAutoReview: 'Auto 审查资格',
  defInstance: '实例',
  defPort: '端口',
  defHomePath: '宿主目录',
  sectionQualifications: '能力准入',
  qualificationsHint: '个人空间的能力资格按用户授予；项目空间同时要求项目授权，在项目详情页和各资源频道管理。',
  qualSshDescription: '远程 SSH 目标上的文件与命令执行资格。',
  qualTerminalName: '终端',
  qualTerminalDescription: '在个人空间打开交互式终端会话的资格。',
  qualDesktopName: '桌面',
  qualDesktopDescription: '申请交互桌面授权的资格，不替代会话内的桌面确认。',
  qualPluginName: '插件管理',
  qualPluginDescription: '在个人空间管理插件（启用、安装、移除）的资格；项目空间另需项目授权。',
  sectionModels: '模型权限',
  modelsMeta: '{count} 个组织模型 · {overrides} 条例外',
  modelsHint: '角色默认与计价在「模型」频道维护；此处只管理该用户的逐模型例外。例外立即生效。',
  loadingModels: '正在加载模型权限',
  modelsEmptyTitle: '还没有组织模型',
  modelsEmptyDetail: '完整模型目录由组织 Provider 配置统一维护。',
  colModel: '模型',
  colRoleDefault: '该账号角色默认',
  userOverride: '此用户例外',
  colEffective: '生效',
  allowed: '允许',
  denied: '拒绝',
  available: '可用',
  roleDefault: '角色默认',
  sectionMemberships: '项目成员',
  membershipsMeta: '{count} 个项目',
  membershipsHintAdmin: '管理员角色对所有项目拥有隐式全权；成员行只为审计与成员列表记录明确授权。',
  membershipsHintUser: '成员行决定该用户在各项目中的目录权限；项目的模型授权在项目详情页管理。',
  loadingMemberships: '正在加载项目成员',
  membershipsEmptyTitle: '不属于任何项目',
  membershipsEmptyDetail: '使用下方表单将此用户加入项目。',
  colProject: '项目',
  colPath: '路径',
  permission: '目录权限',
  colActions: '操作',
  permissionAria: '{name} 目录权限',
  modeReadWrite: '读写',
  modeReadOnly: '只读',
  removeLabel: '移出 {name}',
  joinProjectAria: '要加入的项目',
  selectProject: '选择项目',
  joinProject: '加入项目',
  removeTitle: '移出项目',
  removeDescription: '将 {name} 的成员关系移除此用户；该用户在该项目的私有会话保留但不再可访问。',
  removeConfirm: '确认移出',
  quotaTokenInvalid: 'Token 额度必须是非负整数',
  quotaCostInvalid: '成本额度必须是有效的非负数',
  quotaTokenInherit: 'Token 继承角色',
  quotaTokenUnlimited: 'Token 不限',
  quotaTokenCustom: 'Token {limit}',
  quotaCostInherit: '成本继承角色',
  quotaCostUnlimited: '成本不限',
  quotaCostCustom: '成本 元 {amount}',
  sectionQuota: '配额',
  quotaHint: '额度按自然月统计，在 80% 和 100% 产生告警，但不会阻断模型调用。继承表示跟随其角色的月度额度。',
  loadingQuota: '正在加载配额',
  quotaTokenLabel: 'Token 额度',
  quotaTokenInput: '每月 Token',
  quotaCostLabel: '公司成本额度',
  quotaCostInput: '每月人民币元',
  quotaSave: '保存配额',
  quotaMode: '额度模式',
  quotaModeInherit: '继承角色额度',
  quotaModeUnlimited: '无限制',
  quotaModeCustom: '自定义',
  quotaInheritNote: '跟随其角色的月度额度。',
  quotaUnlimitedNote: '不设置月度上限。',
} satisfies Record<string, string>

export type UserDetailCopyKey = keyof typeof zh

export const en = {
  backToUsers: 'Back to users',
  notFoundTitle: 'User not found',
  notFoundDetail: 'This account may have been deleted.',
  pageTitle: 'User details',
  pageTitleUser: 'User · {name}',
  pageDescription: '@{username} · ID {id} · port {port}',
  editAccount: 'Edit account',
  resetPassword: 'Reset password',
  disable: 'Disable',
  enable: 'Enable',
  deleteAction: 'Delete',
  loadingUser: 'Loading user',
  sectionAccount: 'Account and instance',
  defUsername: 'Username',
  defDisplayName: 'Display name',
  notSet: 'Not set',
  defAutoReview: 'Auto review eligibility',
  defInstance: 'Instance',
  defPort: 'Port',
  defHomePath: 'Home directory',
  sectionQualifications: 'Capability qualifications',
  qualificationsHint: 'Personal-space capability qualifications are granted per user. Project spaces additionally require the project grant, managed on the project detail page and in each resource channel.',
  qualSshDescription: 'Qualification for file access and command execution on remote SSH targets.',
  qualTerminalName: 'Terminal',
  qualTerminalDescription: 'Qualification to open interactive terminal sessions in the personal space.',
  qualDesktopName: 'Desktop',
  qualDesktopDescription: 'Qualification to request interactive desktop authorization; it does not replace the in-session desktop confirmation.',
  qualPluginName: 'Plugin management',
  qualPluginDescription: 'Qualification to manage plugins in the personal space (enable, install, remove); project spaces additionally require the project grant.',
  sectionModels: 'Model permissions',
  modelsMeta: '{count} organization models · {overrides} overrides',
  modelsHint: 'Role defaults and pricing are maintained in the Models channel; this page only manages per-model overrides for this user. Overrides take effect immediately.',
  loadingModels: 'Loading model permissions',
  modelsEmptyTitle: 'No organization models yet',
  modelsEmptyDetail: 'The full model catalog is maintained centrally in the organization provider configuration.',
  colModel: 'Model',
  colRoleDefault: 'Role default for this account',
  userOverride: 'User override',
  colEffective: 'Effective',
  allowed: 'Allowed',
  denied: 'Denied',
  available: 'Available',
  roleDefault: 'Role default',
  sectionMemberships: 'Project memberships',
  membershipsMeta: '{count} projects',
  membershipsHintAdmin: 'The administrator role has implicit full access to every project; membership rows only record explicit grants for audit and the member list.',
  membershipsHintUser: 'Membership rows determine this user’s directory permission in each project; project model grants are managed on the project detail page.',
  loadingMemberships: 'Loading project memberships',
  membershipsEmptyTitle: 'Not a member of any project',
  membershipsEmptyDetail: 'Use the form below to add this user to a project.',
  colProject: 'Project',
  colPath: 'Path',
  permission: 'Directory permission',
  colActions: 'Actions',
  permissionAria: '{name} directory permission',
  modeReadWrite: 'Read-write',
  modeReadOnly: 'Read-only',
  removeLabel: 'Remove {name}',
  joinProjectAria: 'Project to join',
  selectProject: 'Select a project',
  joinProject: 'Join project',
  removeTitle: 'Remove from project',
  removeDescription: 'Removes this user’s membership in {name}; the user’s private sessions in that project are kept but become inaccessible.',
  removeConfirm: 'Confirm removal',
  quotaTokenInvalid: 'The token quota must be a non-negative integer',
  quotaCostInvalid: 'The cost quota must be a valid non-negative number',
  quotaTokenInherit: 'Token inherits role',
  quotaTokenUnlimited: 'Token unlimited',
  quotaTokenCustom: 'Token {limit}',
  quotaCostInherit: 'Cost inherits role',
  quotaCostUnlimited: 'Cost unlimited',
  quotaCostCustom: 'Cost {amount} CNY',
  sectionQuota: 'Quota',
  quotaHint: 'Usage is tallied per calendar month, raising alerts at 80% and 100% without blocking model calls. Inherit means following the role’s monthly quota.',
  loadingQuota: 'Loading quota',
  quotaTokenLabel: 'Token quota',
  quotaTokenInput: 'Tokens per month',
  quotaCostLabel: 'Company cost quota',
  quotaCostInput: 'CNY per month',
  quotaSave: 'Save quota',
  quotaMode: 'Quota mode',
  quotaModeInherit: 'Inherit role quota',
  quotaModeUnlimited: 'Unlimited',
  quotaModeCustom: 'Custom',
  quotaInheritNote: 'Follows the role’s monthly quota.',
  quotaUnlimitedNote: 'No monthly cap is set.',
} satisfies Record<UserDetailCopyKey, string>
