/** User list page copy: header, account table, empty state, and row actions. */

export const zh = {
  pageTitle: '用户管理',
  pageDescription: '管理账号权限、登录状态和每位用户的独立 Harness 实例。点击用户进入详情页管理准入资格、模型例外、项目成员和配额。',
  userCount: '{count} 位用户',
  createUser: '新建用户',
  sectionTitle: '账号与实例',
  recordCount: '{count} 条记录',
  loadingUsers: '正在加载用户',
  emptyTitle: '还没有用户',
  emptyDetail: '创建第一个账号后，可在这里配置角色并控制其 Harness 实例。',
  colUser: '用户',
  colRole: '角色',
  colAutoReview: 'Auto 审查资格',
  colAccount: '账号',
  colInstance: '实例',
  colPort: '端口',
  colActions: '操作',
  detail: '详情',
  edit: '编辑',
  password: '密码',
  disable: '禁用',
  enable: '启用',
  deleteAction: '删除',
  manageDetail: '管理详情',
  editUser: '编辑用户',
  resetPassword: '重置密码',
  disableUser: '禁用用户',
  enableUser: '启用用户',
  deleteUser: '删除用户',
} satisfies Record<string, string>

export type UsersCopyKey = keyof typeof zh

export const en = {
  pageTitle: 'User management',
  pageDescription: 'Manage account permissions, sign-in status, and each user’s dedicated Harness instance. Open a user to manage qualifications, model overrides, project memberships, and quota.',
  userCount: '{count} users',
  createUser: 'New user',
  sectionTitle: 'Accounts and instances',
  recordCount: '{count} records',
  loadingUsers: 'Loading users',
  emptyTitle: 'No users yet',
  emptyDetail: 'After creating the first account, you can configure its role and control its Harness instance here.',
  colUser: 'User',
  colRole: 'Role',
  colAutoReview: 'Auto review eligibility',
  colAccount: 'Account',
  colInstance: 'Instance',
  colPort: 'Port',
  colActions: 'Actions',
  detail: 'Details',
  edit: 'Edit',
  password: 'Password',
  disable: 'Disable',
  enable: 'Enable',
  deleteAction: 'Delete',
  manageDetail: 'Manage details',
  editUser: 'Edit user',
  resetPassword: 'Reset password',
  disableUser: 'Disable user',
  enableUser: 'Enable user',
  deleteUser: 'Delete user',
} satisfies Record<UsersCopyKey, string>
