/** Webhook administration copy: endpoint registry, delivery receipts, and administrator redispatch. */

export const zh = {
  operationFailed: '无法完成 Webhook 操作',
  validationPositiveInteger: '{label}必须是正整数',
  validationMax: '{label}不能超过 {max}',
  validationRequired: '{label}不能为空',
  validationMaxChars: '{label}不能超过 {max} 字符',
  validationModelPair: '模型提供方与模型标识必须同时填写',
  validationExecutionUser: '必须选择执行账号',
  validationRuntimeTarget: '必须选择目标运行时',
  validationFilterCount: '每种筛选最多 64 项',
  validationFilterChars: '筛选项不能超过 128 字符',
  validationRepository: '仓库筛选必须是 owner/repo 完整名',
  validationSecret: '注册时必须填写签名密钥',
  receiptSubmitted: '已受理',
  receiptIgnored: '已忽略',
  receiptRejected: '已拒绝',
  receiptDispatching: '派发中',
  receiptUnknown: '结果未知',
  pageDescription: '登记的 Provider 端点、投递回执和管理员重跑。',
  sectionEndpoints: '接入端点',
  refresh: '刷新',
  registerEndpoint: '注册端点',
  loadingEndpoints: '正在加载 Webhook 端点',
  endpointsEmptyTitle: '尚无 Webhook 端点',
  endpointsEmptyDetail: '注册端点后，Provider 投递经签名验证、结构化筛选和持久去重，再派发到绑定的运行时创建会话。',
  endpointsTableAria: 'Webhook 接入端点，可横向滚动',
  columnSource: '来源',
  columnStatus: '状态',
  columnActions: '操作',
  filterAll: '全部',
  listSeparator: '、',
  parenthesized: '（{value}）',
  runtimeKindUser: '个人',
  runtimeKindProject: '项目',
  statusEnabled: '已启用',
  statusDisabled: '已停用',
  deliveriesLabel: '投递记录',
  edit: '编辑',
  enable: '启用',
  disable: '停用',
  delete: '删除',
  dialogRegisterTitle: '注册 Webhook 端点',
  dialogEditTitle: '编辑 {name}',
  dialogDescription: '接入地址为 /webhook/{端点号}；签名密钥只进不出，留空表示不轮换。模板可引用 {{delivery.id}}、{{event.name}}、{{event.action}} 和 {{payload.*}}。',
  cancel: '取消',
  save: '保存',
  fieldName: '名称',
  hintName: '组织内唯一的管理显示名。',
  fieldSource: '来源标识',
  hintSource: '写入会话来源的部署标识，如 github 组织名。',
  fieldSecret: '签名密钥',
  hintSecretRegister: 'Provider 端配置的 Webhook Secret。',
  hintSecretEdit: '留空保留现有密钥；填写即轮换。',
  fieldEvents: '事件筛选',
  hintEvents: '逗号分隔的事件名，如 push, pull_request；留空接收全部。',
  fieldActions: '动作筛选',
  hintActions: '逗号分隔的 payload.action 值；留空不过滤。',
  fieldRepositories: '仓库筛选',
  hintRepositories: '逗号分隔的 owner/repo 完整名，如 acme/api；留空接收全部仓库。',
  fieldTitleTemplate: '会话标题模板',
  hintTitleTemplate: '支持 {{…}} 占位符。',
  fieldPromptTemplate: '提示词模板',
  hintPromptTemplate: '投递触发会话的首条指令文本。',
  fieldWorkspacePath: '工作区路径',
  hintWorkspacePath: '会话工作区的绝对路径。',
  fieldAgentPreset: '代理预设',
  fieldPermissionPreset: '权限预设',
  fieldModelProvider: '模型提供方',
  hintModelProvider: '留空使用运行时默认模型。',
  fieldModelId: '模型标识',
  fieldModelMaxTokens: '模型令牌上限',
  fieldExecutionUser: '执行账号',
  hintExecutionUser: '投递创建的会话归属此账号。',
  optionSelectAccount: '选择账号',
  fieldRuntimeKind: '运行时类型',
  optionRuntimeUser: '个人运行时',
  optionRuntimeProject: '项目运行时',
  fieldRuntimeTarget: '目标运行时',
  hintRuntimeTarget: '空闲回收的实例可自动唤醒；手动停止、停用或维护时不派发。',
  optionSelectTarget: '选择目标',
  fieldVisibility: '新会话可见性',
  hintVisibility: '私有会话仅执行账号及管理员可见；项目成员仍受原有读写权限限制。',
  optionVisibilityProject: '项目可见',
  optionVisibilityPrivate: '执行账号私有',
  fieldIntakeLimit: '接收限值',
  hintIntakeLimit: '每个窗口内接受的新投递数。',
  labelIntakeWindow: '接收窗口',
  fieldIntakeWindowMs: '接收窗口（毫秒）',
  labelReplayWindow: '重放窗口',
  fieldReplayWindowMs: '重放窗口（毫秒）',
  hintReplayWindow: '正文相同的换号投递在该窗口内归并到原始回执。',
  labelMaxBodyBytes: '请求体上限',
  fieldMaxBodyBytes: '请求体上限（字节）',
  deliveriesTitle: '{name} 的投递记录',
  deliveriesDescription: '回执只保留投递标识、配置代次和结果；已落定的投递可由管理员重跑。',
  deliveriesEmpty: '尚无投递',
  deliveriesTableAria: 'Webhook 投递记录，可横向滚动',
  columnDeliveryId: '投递标识',
  columnRevision: '配置代次',
  columnSession: '会话',
  columnReceivedAt: '接收时间',
  redispatch: '重跑',
  loadMore: '加载更多',
  deleteTitle: '删除 {name}',
  deleteDescription: '删除后端点立即停止接收投递；既有回执保留用于审计。',
  noticeRegistered: 'Webhook 端点已注册。',
  noticeUpdated: 'Webhook 端点已更新。',
  noticeEnabled: '已启用 {name}。',
  noticeDisabled: '已停用 {name}。',
  noticeDeleted: '已删除 {name}。',
  noticeRedispatched: '已重新派发 {delivery}，新回执状态为 {state}。',
} satisfies Record<string, string>

export type WebhooksCopyKey = keyof typeof zh

export const en = {
  operationFailed: 'The webhook operation could not be completed',
  validationPositiveInteger: '{label} must be a positive integer',
  validationMax: '{label} must not exceed {max}',
  validationRequired: '{label} must not be empty',
  validationMaxChars: '{label} must not exceed {max} characters',
  validationModelPair: 'Model provider and model ID must be set together',
  validationExecutionUser: 'An execution account must be selected',
  validationRuntimeTarget: 'A target runtime must be selected',
  validationFilterCount: 'At most 64 entries per filter',
  validationFilterChars: 'Filter entries must not exceed 128 characters',
  validationRepository: 'Repository filters must be full owner/repo names',
  validationSecret: 'A signing secret is required at registration',
  receiptSubmitted: 'Accepted',
  receiptIgnored: 'Ignored',
  receiptRejected: 'Rejected',
  receiptDispatching: 'Dispatching',
  receiptUnknown: 'Outcome unknown',
  pageDescription: 'Registered provider endpoints, delivery receipts, and administrator redispatch.',
  sectionEndpoints: 'Intake endpoints',
  refresh: 'Refresh',
  registerEndpoint: 'Register endpoint',
  loadingEndpoints: 'Loading webhook endpoints',
  endpointsEmptyTitle: 'No webhook endpoints yet',
  endpointsEmptyDetail: 'Once an endpoint is registered, provider deliveries pass signature verification, structured filtering, and durable deduplication before being dispatched to the bound runtime to create sessions.',
  endpointsTableAria: 'Webhook intake endpoints, horizontally scrollable',
  columnSource: 'Source',
  columnStatus: 'Status',
  columnActions: 'Actions',
  filterAll: 'All',
  listSeparator: ', ',
  parenthesized: ' ({value})',
  runtimeKindUser: 'Personal',
  runtimeKindProject: 'Project',
  statusEnabled: 'Enabled',
  statusDisabled: 'Disabled',
  deliveriesLabel: 'Deliveries',
  edit: 'Edit',
  enable: 'Enable',
  disable: 'Disable',
  delete: 'Delete',
  dialogRegisterTitle: 'Register webhook endpoint',
  dialogEditTitle: 'Edit {name}',
  dialogDescription: 'The intake URL is /webhook/<endpoint id>; the signing secret is write-only — leave it blank to keep the current one. Templates may reference {{delivery.id}}, {{event.name}}, {{event.action}}, and {{payload.*}}.',
  cancel: 'Cancel',
  save: 'Save',
  fieldName: 'Name',
  hintName: 'A display name unique within the organization.',
  fieldSource: 'Source identifier',
  hintSource: 'The deployment identifier written into session sources, such as a GitHub organization name.',
  fieldSecret: 'Signing secret',
  hintSecretRegister: 'The webhook secret configured on the provider.',
  hintSecretEdit: 'Leave blank to keep the current secret; enter a value to rotate it.',
  fieldEvents: 'Event filter',
  hintEvents: 'Comma-separated event names, such as push, pull_request; leave blank to receive all.',
  fieldActions: 'Action filter',
  hintActions: 'Comma-separated payload.action values; leave blank for no filtering.',
  fieldRepositories: 'Repository filter',
  hintRepositories: 'Comma-separated owner/repo full names, such as acme/api; leave blank to receive all repositories.',
  fieldTitleTemplate: 'Session title template',
  hintTitleTemplate: 'Supports {{…}} placeholders.',
  fieldPromptTemplate: 'Prompt template',
  hintPromptTemplate: 'The first instruction text for sessions triggered by deliveries.',
  fieldWorkspacePath: 'Workspace path',
  hintWorkspacePath: 'The absolute path of the session workspace.',
  fieldAgentPreset: 'Agent preset',
  fieldPermissionPreset: 'Permission preset',
  fieldModelProvider: 'Model provider',
  hintModelProvider: 'Leave blank to use the runtime default model.',
  fieldModelId: 'Model ID',
  fieldModelMaxTokens: 'Model token limit',
  fieldExecutionUser: 'Execution account',
  hintExecutionUser: 'Sessions created by deliveries belong to this account.',
  optionSelectAccount: 'Select an account',
  fieldRuntimeKind: 'Runtime type',
  optionRuntimeUser: 'Personal runtime',
  optionRuntimeProject: 'Project runtime',
  fieldRuntimeTarget: 'Target runtime',
  hintRuntimeTarget: 'Idle-reclaimed instances can wake automatically; no dispatch while stopped manually, disabled, or under maintenance.',
  optionSelectTarget: 'Select a target',
  fieldVisibility: 'New session visibility',
  hintVisibility: 'Private sessions are visible only to the execution account and administrators; project members keep their existing read/write permissions.',
  optionVisibilityProject: 'Visible to project',
  optionVisibilityPrivate: 'Private to execution account',
  fieldIntakeLimit: 'Intake limit',
  hintIntakeLimit: 'New deliveries accepted within each window.',
  labelIntakeWindow: 'Intake window',
  fieldIntakeWindowMs: 'Intake window (ms)',
  labelReplayWindow: 'Replay window',
  fieldReplayWindowMs: 'Replay window (ms)',
  hintReplayWindow: 'Repeated deliveries with identical bodies fold into the original receipt within this window.',
  labelMaxBodyBytes: 'Request body limit',
  fieldMaxBodyBytes: 'Request body limit (bytes)',
  deliveriesTitle: 'Deliveries for {name}',
  deliveriesDescription: 'Receipts keep only the delivery ID, configuration revision, and outcome; settled deliveries can be rerun by an administrator.',
  deliveriesEmpty: 'No deliveries yet',
  deliveriesTableAria: 'Webhook deliveries, horizontally scrollable',
  columnDeliveryId: 'Delivery ID',
  columnRevision: 'Config revision',
  columnSession: 'Session',
  columnReceivedAt: 'Received at',
  redispatch: 'Rerun',
  loadMore: 'Load more',
  deleteTitle: 'Delete {name}',
  deleteDescription: 'The endpoint stops receiving deliveries immediately after deletion; existing receipts are kept for auditing.',
  noticeRegistered: 'Webhook endpoint registered.',
  noticeUpdated: 'Webhook endpoint updated.',
  noticeEnabled: '{name} enabled.',
  noticeDisabled: '{name} disabled.',
  noticeDeleted: '{name} deleted.',
  noticeRedispatched: '{delivery} redispatched; the new receipt state is {state}.',
} satisfies Record<WebhooksCopyKey, string>
