/**
 * Source files carried outside the per-file 100% coverage gate as recorded
 * debt. The first hosted-runner execution of the coverage lane (the fork's
 * enterprise runner pool never existed, so the gate never ran) reported these
 * files below the bar; they are listed here explicitly rather than lowering
 * the global threshold or excluding whole packages.
 *
 * Membership contract: the roster only shrinks. Cover a file and delete its
 * line in the same change; never add a file that the gate has already been
 * enforcing. Every path must exist under a `packages/<group>/<pkg>/src` tree
 * (`scripts/coverage-baseline.spec.ts`) so a moved or deleted source cannot
 * leave a stale exclusion behind. The rationale and the shrink path live in
 * the coverage-baseline Agent Note
 * (.agents/notes/implemented/testing/2026-09-02-first-run-coverage-baseline.md).
 */

/** Files the per-file coverage gate skips until their listed debt is paid. */
export const coverageBaselineFiles: readonly string[] = [
  // Personal documents (userdoc storage, upload, HTTP surface, modal). The two
  // largest entries — DocumentsModal.tsx and userdoc-http/index.ts — hold
  // roughly two fifths of the recorded debt.
  'packages/attachment/attachment-local/src/compression-limiter.ts',
  'packages/attachment/attachment-local/src/index.ts',
  'packages/attachment/attachment-local/src/request-image.ts',
  'packages/attachment/attachment-local/src/store.ts',
  'packages/attachment/attachment/src/request-projection.ts',
  'packages/attachment/userdoc-local/src/index.ts',
  'packages/attachment/userdoc-local/src/migration.ts',
  'packages/attachment/userdoc-local/src/name.ts',
  'packages/attachment/userdoc-local/src/store.ts',
  'packages/attachment/userdoc-local/src/trash.ts',
  'packages/attachment/userdoc-local/src/upload.ts',
  'packages/attachment/userdoc/src/index.ts',
  'packages/client/ui-documents/src/client/DocumentPreview.tsx',
  'packages/client/ui-documents/src/client/DocumentsButton.tsx',
  'packages/client/ui-documents/src/client/DocumentsModal.tsx',
  'packages/client/ui-documents/src/client/index.ts',
  'packages/client/ui-documents/src/client/documents-client.ts',
  'packages/client/ui-documents/src/client/userdoc-client.ts',
  'packages/client/userdoc-upload/src/index.ts',
  'packages/host/userdoc-http/src/index.ts',
  // Collaboration and Gateway integration (project scope, shared history,
  // Gateway-backed persistence and archives, the Host fetch bridge).
  'packages/client/ui-collaboration/src/client/ProjectManagerModal.tsx',
  'packages/client/ui-collaboration/src/client/ScopeControl.tsx',
  'packages/client/ui-collaboration/src/client/ScopeSwitchStatus.tsx',
  'packages/client/ui-collaboration/src/client/collaboration-client.ts',
  'packages/client/ui-collaboration/src/client/ConversationShareAction.tsx',
  'packages/client/ui-collaboration/src/client/index.ts',
  'packages/client/ui-collaboration/src/index.ts',
  'packages/context/archive-gateway/src/index.ts',
  'packages/context/collaboration-context/src/invariant.ts',
  'packages/context/collaboration-context/src/participant.ts',
  'packages/context/collaboration-gateway/src/index.ts',
  'packages/context/collaboration/src/index.ts',
  'packages/context/gateway-runtime/src/index.ts',
  'packages/context/file-reference-local/src/search.ts',
  'packages/context/session-reference/src/index.ts',
  'packages/api/gateway/src/client/index.ts',
  'packages/host/apiproxy/src/api/sessions.schema.ts',
  'packages/host/apiproxy/src/fetch/client.ts',
  'packages/host/apiproxy/src/fetch/handler.ts',
  'packages/host/apiproxy/src/fetch/history-wire.ts',
  'packages/host/apiproxy/src/history-index.ts',
  'packages/host/apiproxy/src/session-export.ts',
  'packages/session/session-persistence-gateway/src/index.ts',
  // LLM adapters and usage accounting.
  'packages/llm/llm-deepseek/src/adapter.ts',
  'packages/llm/llm-deepseek/src/files-api.ts',
  'packages/llm/llm-deepseek/src/index.ts',
  'packages/llm/llm-deepseek/src/request-pricing.ts',
  'packages/llm/llm-deepseek/src/translate.ts',
  'packages/llm/llm-pi-ai/src/auth.ts',
  'packages/llm/llm-pi-ai/src/index.ts',
  'packages/llm/llm-pi-ai/src/login.ts',
  'packages/llm/llm/src/attribution.ts',
  'packages/llm/llm/src/content.ts',
  'packages/llm/llm/src/text-thinking-guard.ts',
  'packages/llm/token-meter/src/route-pricing.ts',
  'packages/llm/token-meter/src/turn-usage.ts',
  // Sub-agent delegation and its model-selection settings.
  'packages/subagent/subagent-dsh-sdk/src/index.ts',
  'packages/subagent/subagent/src/child-agent.ts',
  'packages/subagent/subagent/src/index.ts',
  'packages/subagent/tool-subagent/src/index.ts',
  'packages/subagent/tool-subagent/src/list-models.ts',
  'packages/subagent/tool-subagent/src/model-selection-settings.ts',
  'packages/subagent/tool-subagent/src/model-selection-state.ts',
  'packages/subagent/tool-subagent/src/model-selection.ts',
  // Session persistence backends and log export.
  'packages/session-query/session-log-export/src/client/HeaderAction.tsx',
  'packages/session-query/session-log-export/src/client/index.ts',
  'packages/session/session-log-deepseek/src/index.ts',
  'packages/session/session-persistence-jsonl/src/index.ts',
  'packages/session/session-persistence-jsonl/src/zstd-public-decoder.ts',
  'packages/session/session-persistence-jsonl/src/zstd.ts',
  'packages/session/session-persistence-sqlite/src/index.ts',
  'packages/session/session-persistence-sqlite/src/store.ts',
  'packages/session/session-persistence/src/index.ts',
  'packages/session/session-persistence/src/page.ts',
  'packages/session/session-persistence-sqlite/src/compression.ts',
  // SDK, ACP, and Remote lookup transports.
  'packages/acp/acp/src/index.ts',
  'packages/api/remotes/src/agent-lookup.ts',
  'packages/sdk/client/src/client.ts',
  'packages/sdk/client/src/api.ts',
  'packages/sdk/protocol/src/transport.ts',
  'packages/sdk/server/src/index.ts',
  'packages/sdk/server/src/server.ts',
  // Browser client surfaces not yet under the GUI debt exemptions in
  // vitest.config.ts (settings tabs, theme, presets, connection).
  'packages/client/connection/src/client/connection.ts',
  'packages/client/connection/src/client/index.ts',
  'packages/client/connection/src/client/web-api-client.ts',
  'packages/client/connection/src/websocket-downlink.ts',
  'packages/client/locale/src/client/LanguageRow.tsx',
  'packages/client/runtime/src/client/contract/settings-scope.ts',
  'packages/client/ui-agent-preset/src/client/AgentPresetRow.tsx',
  'packages/client/ui-agent-preset/src/client/section-store.ts',
  'packages/client/ui-agent-preset/src/client/settings-store.ts',
  'packages/client/ui-attachment/src/MessageImage.tsx',
  'packages/client/ui-input-trigger/src/client/MenuView.tsx',
  'packages/client/ui-input-trigger/src/client/index.ts',
  'packages/client/ui-permission-presets/src/client/PermissionRow.tsx',
  'packages/client/ui-primitives/src/dialog-focus.ts',
  'packages/client/ui-primitives/src/markdown/CodeBlock.tsx',
  'packages/client/ui-primitives/src/markdown/JsonBlock.tsx',
  'packages/client/ui-primitives/src/Modal.tsx',
  'packages/client/ui-primitives/src/DiffBlock.tsx',
  'packages/client/ui-primitives/src/ReadBlock.tsx',
  'packages/client/ui-primitives/src/SearchBlock.tsx',
  'packages/client/ui-primitives/src/markdown/render.tsx',
  'packages/client/ui-primitives/src/use-media-query.ts',
  'packages/client/ui-reference/src/client/index.ts',
  'packages/client/ui-settings-general/src/client/SettingsRoot.tsx',
  'packages/client/ui-settings-models/src/client/ModelListEditor.tsx',
  'packages/client/ui-settings-models/src/client/ModelsSection.tsx',
  'packages/client/ui-settings-models/src/client/index.ts',
  'packages/client/ui-settings-models/src/client/model-capabilities.ts',
  'packages/client/ui-settings-plugin-inventory/src/client/PluginInventorySettingsTab.tsx',
  'packages/client/ui-settings-plugin-inventory/src/client/index.ts',
  'packages/client/ui-settings-plugins/src/client/PluginCard.tsx',
  'packages/client/ui-settings/src/client/index.ts',
  'packages/client/ui-settings/src/client/settings-scope.ts',
  'packages/client/ui-settings-general/src/client/index.ts',
  'packages/client/ui-settings-models/src/client/store.ts',
  'packages/client/ui-settings-models/src/client/ProviderEditor.tsx',
  'packages/client/ui-settings-models/src/client/DeepSeekModelsEditor.tsx',
  'packages/client/ui-settings-plugins/src/client/card-form.ts',
  'packages/client/ui-permission-presets/src/client/settings-store.ts',
  'packages/client/ui-jobs/src/client/JobListAction.tsx',
  'packages/client/ui-subagent/src/client/SubagentHeaderLineage.tsx',
  'packages/client/ui-workspace/src/client/tree.ts',
  'packages/client/ui-workspace/src/client/rows/Rows.tsx',
  'packages/client/ui-theme/src/boot-theme.ts',
  'packages/client/ui-theme/src/client/AppearanceRow.tsx',
  'packages/client/ui-theme/src/client/index.ts',
  'packages/client/ui-theme/src/client/settings-store.ts',
  'packages/client/ui-theme/src/index.ts',
  // Host-side runtime pieces with fork-added branches awaiting tests.
  'packages/core/agent-loop/src/index.ts',
  'packages/core/agent-loop/src/agent.ts',
  'packages/core/tools/src/index.ts',
  'packages/core/agent/src/inbox.ts',
  'packages/core/tools/src/code-mode.ts',
  'packages/credentials/credentials/src/index.ts',
  'packages/fs/fs/src/index.ts',
  'packages/goal/goal/src/index.ts',
  'packages/goal/tool-goal/src/authority.ts',
  'packages/host/plugin-inventory/src/index.ts',
  'packages/interaction/permission-presets/src/index.ts',
  'packages/preset/agent-presets/src/mount.ts',
  'packages/preset/agent-presets/src/index.ts',
  'packages/preset/agent-presets/src/discovery.ts',
  'packages/preset/agent-presets/src/specifier.ts',
  'packages/settings/settings/src/redact.ts',
  'packages/test-support/acp-snapshot/src/normalize.ts',
  'packages/test-support/acp-snapshot/src/suite.ts',
  'packages/test-support/client-runtime/src/sessions.ts',
  'packages/test-support/llm-replay/src/index.ts',
  'packages/web/web/src/response.ts',
  'packages/web/web-fetch-http/src/provider.ts',
  'packages/spill/spill-policy/src/index.ts',
  'packages/fs/fs-local/src/index.ts',
  'packages/examples/agent-spine-demo/src/index.ts',
  'packages/workspace/workspace/src/index.ts',
  'packages/subagent/subagent-acp/src/run.ts',
  'packages/subagent/subagent/src/list-children.ts',
  'packages/subagent/subagent/src/descriptor.ts',
  'packages/subagent/subagent/src/continuation.ts',
  'packages/subagent/subagent-dsh-sdk/src/run.ts',
]
